import React, { useState } from 'react';
import { View, ScrollView, useWindowDimensions } from 'react-native';
import { useStore } from './store';
import { Dealer, Role, uid } from './domain';
import { C,s,Card,Row,Txt,Button,SectionTitle,Field,Select,Banner,Badge,BatteryArt,Icon } from './ui';
export function Auth({onEnter}:{onEnter:()=>void}) {
 const {state,setState,setRole,setDealerId,notify,audit}=useStore();const [page,setPage]=useState('login'),[role,setLocalRole]=useState<Role>('Dealer'),[identity,setIdentity]=useState(''),[password,setPassword]=useState(''),[otp,setOtp]=useState(''),[error,setError]=useState('');const [registration,setRegistration]=useState<Dealer>({id:uid('DLR'),name:'',contact:'',mobile:'',email:'',city:'Dhule',place:'',address:'',pin:'',state:'Maharashtra',status:'Pending Approval'});const wide=useWindowDimensions().width>900;
 const enter=()=>{if(otp!=='123456'){setError('Use the demo code 123456.');return;}if(role==='Dealer'){const dealer=state.dealers.find(d=>d.mobile===identity||d.email===identity);if(!dealer){setError('No demo dealer matches. Try 9876543210 or register a dealership.');return;}if(dealer.status==='Pending Approval'||dealer.status==='Rejected'){setError(`Account ${dealer.status.toLowerCase()}. ${dealer.reason||'An admin needs to approve your registration.'}`);return;}setDealerId(dealer.id);}setRole(role);onEnter();};
 return <View style={{flex:1,flexDirection:'row',backgroundColor:C.bg}}>{wide&&<View style={{width:'46%',backgroundColor:C.nav,padding:60,justifyContent:'space-between'}}><Row><Icon name="zap" color={C.gold} size={30}/><Txt style={{color:'white',fontSize:30,fontWeight:'800',letterSpacing:3}}>FELIX</Txt></Row><View style={{gap:22}}><BatteryArt size={330}/><Txt style={{fontSize:42,fontWeight:'600',lineHeight:51,color:'white'}}>Power that lasts.{'\n'}Connections that matter.</Txt><Txt style={{color:'#A6B2BC',fontSize:15,lineHeight:25}}>Your battery lifecycle, dealer network, and every service relationship. All in one workspace.</Txt></View><Txt style={{fontSize:10,color:'#7C8993',letterSpacing:2}}>FELIX BATTERIES INDUSTRIES</Txt></View>}<ScrollView contentContainerStyle={{flexGrow:1,justifyContent:'center',padding:wide?54:24}} keyboardShouldPersistTaps="handled"><View style={{width:'100%',maxWidth:470,alignSelf:'center'}}><Row style={{marginBottom:38}}><Icon name="zap" size={24} color="#B98522"/><Txt style={{fontSize:24,fontWeight:'800',letterSpacing:2}}>FELIX</Txt><Txt style={s.caption}>DEALER WORKSPACE</Txt></Row>
 {page==='login'&&<><SectionTitle title="Welcome back" sub="Sign in to keep your business powered."/><Select label="Workspace role" value={role} options={['Dealer','Main Admin','Co-Admin','Read-only']} onChange={r=>setLocalRole(r as Role)}/><Field label="Mobile number or email" value={identity} onChange={setIdentity} placeholder={role==='Dealer'?'9876543210':'admin@example.com'}/><Field label="Password" value={password} onChange={setPassword} secure placeholder="Demo: enter any 8 characters"/>{error&&<Banner tone="danger" text={error}/>}<Button label="Continue to verification" icon="arrow-right" onPress={()=>{if(!identity.trim()||password.length<8){setError('Enter an identity and a demo password of at least 8 characters.');return;}setError('');setPage('otp');}}/><Button label="Forgot password?" kind="ghost" onPress={()=>{setError('');setPage('recovery');}}/><View style={s.divider}/><Button label="Register your dealership" kind="secondary" onPress={()=>setPage('register')}/><View style={{marginTop:22}}><Banner text="Frontend demo · no password is stored or transmitted. To explore instantly, use the demo workspace below."/></View><Button label="Explore demo workspace" kind="ghost" onPress={()=>{setRole('Dealer');setDealerId('FPP-014');onEnter();}}/></>}
 {page==='otp'&&<><SectionTitle title="Verify your sign-in" sub="This is a local preview. No SMS or email has been sent."/><Banner text="Demo verification code: 123456"/><Field label="Six-digit verification code" value={otp} onChange={setOtp} numeric error={error}/><Button label="Verify & sign in" onPress={enter}/><Button label="Back to sign-in" kind="ghost" onPress={()=>setPage('login')}/></>}
 {page==='recovery'&&<><SectionTitle title="Recover your account" sub="Preview the recovery flow using a demo verification code."/><Field label="Registered mobile / email" value={identity} onChange={setIdentity}/><Button label="Request recovery code" onPress={()=>{if(!identity.trim()){notify('Enter the registered mobile or email.');return;}setPage('reset');}}/><Button label="Back to sign-in" kind="ghost" onPress={()=>setPage('login')}/></>}
 {page==='reset'&&<><Banner text="Demo recovery code: 123456. A production reset endpoint is not connected."/><Field label="Verification code" value={otp} onChange={setOtp} numeric/><Field label="New demo password" value={password} onChange={setPassword} secure/><Button label="Preview password reset" onPress={()=>{if(otp!=='123456'||password.length<8){notify('Use code 123456 and at least 8 password characters.');return;}setPassword('');setOtp('');setPage('login');notify('Reset flow completed locally. No real account credential was changed.');}}/></>}
 {page==='register'&&<><SectionTitle title="Join the Felix network" sub="Your registration will be reviewed by the admin."/>{(['name','contact','mobile','email','state','pin','place','address'] as const).map(k=><Field key={k} label={({name:'Company / dealer name *',contact:'Contact person *',mobile:'Mobile *',email:'Email *',state:'State *',pin:'PIN code *',place:'Place / area',address:'Full address *'})[k]} value={registration[k]} onChange={v=>setRegistration({...registration,[k]:v})}/>)}<Select label="City" value={registration.city} options={state.cities} onChange={city=>setRegistration({...registration,city})}/>{error&&<Banner tone="danger" text={error}/>}<Button label="Submit registration" onPress={()=>{const r=registration;if(!r.name.trim()||!r.contact.trim()||!r.address.trim()||!r.state.trim()||!/^\d{10}$/.test(r.mobile)||!/^\d{6}$/.test(r.pin)||!/^\S+@\S+\.\S+$/.test(r.email)){setError('Complete required fields with a valid mobile, email, and PIN.');return;}if(state.dealers.some(d=>d.mobile===r.mobile||d.email===r.email)){setError('A dealer with this email or mobile already exists.');return;}setState(s=>audit({...s,dealers:[r,...s.dealers]},'Dealer registered',r.id,'Self-registration pending review'));setPage('pending');}}/><Button label="Back to sign-in" kind="ghost" onPress={()=>setPage('login')}/></>}
 {page==='pending'&&<><SectionTitle title="You’re on the list" sub="An admin will review your business details."/><Badge status="Pending Approval"/><Txt style={[s.caption,{marginVertical:24}]}>{registration.name} · {registration.id}</Txt><Banner text="You can sign in once your account is approved. For this demo, open the Admin workspace and review your registration in Dealers."/><Button label="Return to sign-in" onPress={()=>setPage('login')}/></>}
 </View></ScrollView></View>;
}
