import React, { useState } from 'react';
import { View, Pressable, Switch } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { useStore } from './store';
import { Dealer, Customer, Model, uid, today, warranty, expiryFrom } from './domain';
import { C,s,Card,Row,Txt,Button,SectionTitle,Field,Select,Banner,Dialog,ReasonDialog,Badge,Icon,Empty,KeyValue } from './ui';
import { EntryRows, Nav } from './Dashboard';
export function Dealers({nav,id}:{nav:Nav;id?:string}) {
 const {state,setState,role,isAdmin,canEdit,audit,notify}=useStore();const [query,setQuery]=useState(''),[status,setStatus]=useState('All'),[city,setCity]=useState('All'),[action,setAction]=useState('');const d=state.dealers.find(d=>d.id===id);
 if(!isAdmin)return <Empty title="Admin access required"/>;
 if(d)return <View style={{gap:20}}><SectionTitle title={d.name} sub={`${d.id} · ${d.city}`} action="All dealers" onPress={()=>nav('dealers')}/><Card><Badge status={d.status}/><Row style={{flexWrap:'wrap'}}>{[['Contact person',d.contact],['Mobile',d.mobile],['Email',d.email],['Address',d.address],['State / PIN',`${d.state} / ${d.pin}`]].map(([label,value])=><KeyValue key={label} label={label} value={value}/>)}</Row>{d.reason&&<Banner tone="warning" text={d.reason}/>}<KeyValue label="Supporting documents" value={d.documents?.join(', ')||'No documents attached'}/>{canEdit&&<Row style={{flexWrap:'wrap'}}>{(d.status==='Pending Approval'?['Approve','Reject']:d.status==='Active'?['Suspend']:['Activate']).map(a=><Button key={a} label={`${a} dealer`} kind={a==='Reject'||a==='Suspend'?'danger':'primary'} onPress={()=>setAction(a)}/>)}</Row>}</Card><Card><SectionTitle title="Dealer activity"/><EntryRows entries={state.entries.filter(e=>e.dealerId===d.id)} onOpen={e=>nav('entry',e.id)}/></Card><Card><SectionTitle title="Status & audit history"/>{state.audits.filter(a=>a.ref===d.id).map(a=><View key={a.id} style={{paddingVertical:10}}><Txt style={{fontSize:13,fontWeight:'600'}}>{a.action}</Txt><Txt style={s.caption}>{a.reason} · {a.at}</Txt></View>)}</Card><ReasonDialog open={!!action} title={`${action} ${d.name}`} onClose={()=>setAction('')} onConfirm={reason=>{if(state.offline){notify('Dealer decisions require online mode.');return;}const next=action==='Approve'||action==='Activate'?'Active':action==='Reject'?'Rejected':'Suspended';setState(s=>audit({...s,dealers:s.dealers.map(x=>x.id===d.id?{...x,status:next,reason}:x),notices:[{id:uid('N'),title:`Dealer account ${next.toLowerCase()}`,body:reason,route:'profile',read:false,dealerId:d.id},...s.notices]},`${action} dealer`,d.id,reason,d.status,next));notify(`Dealer is now ${next.toLowerCase()}.`);}}/></View>;
 return <View style={{gap:20}}><SectionTitle title="Dealer network" sub="Every relationship, in one place."/><Card><Field label="Search dealers" value={query} onChange={setQuery} placeholder="Name, city, or dealer code"/><Row style={{flexWrap:'wrap'}}><Select label="Account status" value={status} options={['All','Active','Pending Approval','Rejected','Suspended']} onChange={setStatus}/><Select label="Territory / city" value={city} options={['All',...state.cities]} onChange={setCity}/></Row></Card>{state.dealers.filter(d=>(status==='All'||d.status===status)&&(city==='All'||d.city===city)&&[d.name,d.city,d.id].some(v=>v.toLowerCase().includes(query.toLowerCase()))).map(d=><Pressable key={d.id} accessibilityRole="button" onPress={()=>nav('dealer',d.id)}><Card><Row><View style={{width:44,height:44,borderRadius:12,backgroundColor:C.blueSoft,alignItems:'center',justifyContent:'center'}}><Icon name="shopping-bag" color={C.blue}/></View><View style={{flex:1,gap:7}}><Txt style={{fontWeight:'600'}}>{d.name}</Txt><Txt style={s.caption}>{d.id} · {d.city} · {d.contact}</Txt></View><Badge status={d.status}/><Icon name="chevron-right"/></Row></Card></Pressable>)}</View>;
}
export function Customers({nav}:{nav:Nav}) {
 const {state,setState,isAdmin,dealerId,canEdit,audit,notify}=useStore();const [query,setQuery]=useState(''),[editing,setEditing]=useState<Customer|null>(null),[detail,setDetail]=useState<Customer|null>(null),[merge,setMerge]=useState(false),[target,setTarget]=useState('');
 const rows=state.customers.filter(c=>(isAdmin||c.dealerId===dealerId)&&!c.mergedInto&&[c.name,c.mobile,c.equipment].some(v=>v.toLowerCase().includes(query.toLowerCase())));
 const save=()=>{if(!editing)return;if(!editing.name.trim()||!/^\d{10}$/.test(editing.mobile)){notify('Enter a name and a valid 10-digit mobile number.');return;}if(state.customers.some(c=>!c.mergedInto&&c.id!==editing.id&&c.dealerId===editing.dealerId&&c.mobile===editing.mobile)){notify('A customer with this mobile exists. Open the existing record or use merge.');return;}setState(s=>audit({...s,customers:[editing,...s.customers.filter(c=>c.id!==editing.id)]},'Customer saved',editing.id,'Customer profile updated'));setEditing(null);notify('Customer saved.');};
 return <View style={{gap:20}}><SectionTitle title="Customer relationships" sub="Battery history becomes service history."/>{canEdit&&<Button label="Add customer" icon="plus" onPress={()=>setEditing({id:uid('CUS'),dealerId,name:'',mobile:'',address:'',equipment:'',consent:false})}/>}<Card><Field label="Search customers" value={query} onChange={setQuery} placeholder="Name, mobile, or equipment"/></Card>{rows.map(c=><Pressable key={c.id} accessibilityRole="button" onPress={()=>setDetail(c)}><Card><Row><View style={{width:42,height:42,borderRadius:21,backgroundColor:C.goldSoft,alignItems:'center',justifyContent:'center'}}><Txt style={{fontWeight:'600'}}>{c.name.slice(0,2).toUpperCase()}</Txt></View><View style={{flex:1,gap:5}}><Txt style={{fontWeight:'600'}}>{c.name}</Txt><Txt style={s.caption}>{c.mobile} · {c.equipment||'No equipment linked'}</Txt></View><Icon name="chevron-right"/></Row></Card></Pressable>)}
 <Dialog title={editing?'Customer profile':''} open={!!editing} onClose={()=>setEditing(null)}>{editing&&<>{(['name','mobile','address','equipment'] as const).map(k=><Field key={k} label={k==='mobile'?'Mobile *':k==='name'?'Name *':k[0].toUpperCase()+k.slice(1)} value={editing[k]} onChange={v=>setEditing({...editing,[k]:v})}/>)}<Row style={{justifyContent:'space-between',marginBottom:20}}><Txt style={{fontSize:12}}>Consent to service communications</Txt><Switch value={editing.consent} onValueChange={consent=>setEditing({...editing,consent})}/></Row><Button label="Save customer" onPress={save}/></>}</Dialog>
 <Dialog title={detail?.name||''} open={!!detail} onClose={()=>setDetail(null)}>{detail&&<><KeyValue label="Mobile" value={detail.mobile}/><KeyValue label="Address" value={detail.address}/><KeyValue label="Equipment" value={detail.equipment}/><Badge status={detail.consent?'Communication consent recorded':'No communication consent'}/><View style={{marginTop:18}}><SectionTitle title="Service history"/><EntryRows entries={state.entries.filter(e=>e.dealerId===detail.dealerId&&e.customer===detail.name)} onOpen={e=>{setDetail(null);nav('entry',e.id);}}/></View>{canEdit&&<Row style={{flexWrap:'wrap',marginTop:20}}><Button label="Edit customer" onPress={()=>{setEditing(detail);setDetail(null);}}/>{isAdmin&&<Button label="Resolve duplicate" kind="secondary" onPress={()=>{setTarget(state.customers.find(c=>c.id!==detail.id&&c.dealerId===detail.dealerId&&!c.mergedInto)?.id||'');setMerge(true);}}/>}</Row>}</>}</Dialog>
 <ReasonDialog title="Merge duplicate customer" open={merge} onClose={()=>setMerge(false)} extra={<Select label="Keep customer record" value={target} options={state.customers.filter(c=>c.id!==detail?.id&&c.dealerId===detail?.dealerId&&!c.mergedInto).map(c=>c.id)} onChange={setTarget}/>} onConfirm={reason=>{if(!detail||!target)return;const kept=state.customers.find(c=>c.id===target)!;setState(s=>audit({...s,customers:s.customers.map(c=>c.id===detail.id?{...c,mergedInto:target}:c)},'Customer duplicate linked',detail.id,reason,detail.name,kept.name));setDetail(null);notify('Duplicate linked. Original customer identity is retained.');}}/></View>;
}
export function Warranty({nav}:{nav:Nav}) {
 const {state,setState,role,isAdmin,dealerId,canEdit,audit,notify}=useStore();const [tab,setTab]=useState('Warranty register'),[filter,setFilter]=useState('All'),[editor,setEditor]=useState(false),[months,setMonths]=useState('24'),[effective,setEffective]=useState(today()),[anchor,setAnchor]=useState('Original sale'),[overrides,setOverrides]=useState(false),[maxDays,setMaxDays]=useState('0'),[reason,setReason]=useState(''),[decision,setDecision]=useState<{id:string;status:string}|null>(null);
 return <View style={{gap:20}}><SectionTitle title="Warranty & continuity" sub="One original promise. Protected through every replacement."/><Row style={{flexWrap:'wrap'}}>{(isAdmin?['Warranty register','Policy versions','Override requests']:['Warranty register']).map(t=><Button key={t} label={t} kind={tab===t?'primary':'secondary'} onPress={()=>setTab(t)}/>)}</Row>
 {tab==='Warranty register'&&<><Select label="Warranty status" value={filter} options={['All','Active','Expiring soon','Expired','Not on record']} onChange={setFilter}/>{state.batteries.filter(b=>(isAdmin||b.dealerId===dealerId)&&(filter==='All'||warranty(b).status===filter)).map(b=><Pressable key={b.code} accessibilityRole="button" onPress={()=>nav('battery',b.code)}><Card><Row style={{justifyContent:'space-between'}}><View style={{gap:7}}><Txt style={{fontWeight:'600'}}>{b.code} · {b.model}</Txt><Txt style={s.caption}>{b.customer||'Available stock'} · expires {b.expiry||'Not activated'}</Txt></View><Badge status={warranty(b).status}/></Row></Card></Pressable>)}</>}
 {tab==='Policy versions'&&<><Banner text="New policy versions apply to eligible future sales. Existing chains retain their original policy, start, and expiry."/>{role==='Main Admin'&&<Button label="Create policy version" icon="plus" onPress={()=>setEditor(true)}/>} {state.policies.map(p=><Card key={p.id}><SectionTitle title={p.id} sub={`Effective ${p.effective}`}/><Row style={{flexWrap:'wrap'}}><KeyValue label="Standard term" value={`${p.months} months`}/><KeyValue label="Warranty anchor" value={p.anchor}/><KeyValue label="Replacement method" value="Continue original warranty"/><KeyValue label="Overrides" value={p.overrides?`Up to ${p.maxDays} days`:'Not permitted'}/></Row></Card>)}</>}
 {tab==='Override requests'&&<>{!state.overrides.length&&<Empty title="No override requests" text="Requests raised from a battery detail will appear here."/>}{state.overrides.map(o=><Card key={o.id}><SectionTitle title={o.code} sub={`Requested extension: ${o.days} days`}/><Badge status={o.status}/><KeyValue label="Reason" value={o.reason}/>{canEdit&&o.status==='Pending'&&<Row><Button label="Approve override" onPress={()=>setDecision({id:o.id,status:'Approved'})}/><Button label="Reject override" kind="danger" onPress={()=>setDecision({id:o.id,status:'Rejected'})}/></Row>}</Card>)}</>}
 <Dialog title="New warranty policy version" open={editor} onClose={()=>setEditor(false)}><Field label="Standard term (months)" value={months} onChange={setMonths} numeric/><Field label="Effective date (YYYY-MM-DD)" value={effective} onChange={setEffective}/><Select label="Calculation anchor" value={anchor} options={['Original sale','Activation']} onChange={setAnchor}/><Row style={{justifyContent:'space-between',marginBottom:18}}><Txt>Allow approved overrides</Txt><Switch value={overrides} onValueChange={setOverrides}/></Row><Field label="Maximum extension days" value={maxDays} onChange={setMaxDays} numeric/><Field label="Policy change reason *" value={reason} onChange={setReason} multiline/><Button label="Save policy version" onPress={()=>{if(!/^\d+$/.test(months)||Number(months)<1||!/^\d+$/.test(maxDays)||!/^\d{4}-\d{2}-\d{2}$/.test(effective)||effective<today()||!Number.isFinite(Date.parse(effective))||reason.trim().length<5){notify('Use a future effective date, a positive term, and a reason.');return;}setState(s=>audit({...s,policies:[{id:uid('POL'),months:Number(months),effective,anchor,overrides,maxDays:Number(maxDays),alertDays:30},...s.policies]},'Policy version created','POLICY',reason));setEditor(false);notify('New policy version saved. Existing chains are unchanged.');}}/></Dialog>
 <ReasonDialog title={`${decision?.status==='Approved'?'Approve':'Reject'} override`} open={!!decision} onClose={()=>setDecision(null)} onConfirm={why=>{if(!decision)return;const o=state.overrides.find(o=>o.id===decision.id)!;const b=state.batteries.find(b=>b.code===o.code);const p=state.policies.find(p=>p.id===b?.policy);if(decision.status==='Approved'&&(!p?.overrides||o.days>p.maxDays||!b?.expiry)){notify('The battery’s original policy does not permit this extension. Request cannot be approved.');return;}setState(s=>{const end=b?.expiry?new Date(Date.parse(b.expiry)+o.days*86400000).toISOString().slice(0,10):undefined;return audit({...s,overrides:s.overrides.map(x=>x.id===o.id?{...x,status:decision.status}:x),batteries:decision.status==='Approved'?s.batteries.map(x=>x.code===o.code?{...x,expiry:end}:x):s.batteries},`Warranty override ${decision.status.toLowerCase()}`,o.code,why,b?.expiry,end);});notify('Override decision recorded.');}}/></View>;
}
