import React, { useState } from 'react';
import { View, Image, Pressable } from 'react-native';
import { useStore } from './store';
import { Entry, filterEntries, approveEntry, validateEntry, warranty, chainFor, dateLabel, uid, today } from './domain';
import { C, s, Txt, Row, Card, Button, Badge, SectionTitle, Banner, Field, Select, KeyValue, Empty, ReasonDialog, Icon } from './ui';
import { EntryRows, Nav } from './Dashboard';
import { printEntry } from './reports';
export function Activity({nav,mode='activity'}:{nav:Nav;mode?:string}) {
 const {state,isAdmin,dealerId}=useStore();const [query,setQuery]=useState(''),[type,setType]=useState('All'),[status,setStatus]=useState('All'),[model,setModel]=useState('All'),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const base=state.entries.filter(e=>(isAdmin||e.dealerId===dealerId)&&(mode==='approvals'?['Submitted','Under Review','Conflict'].includes(e.status):mode==='corrections'?e.correction?.status==='Pending':true));
 const rows=filterEntries(base,query,type,status,model,from,to);
 return <View style={{gap:20}}><SectionTitle title={mode==='approvals'?'Requests & exceptions':mode==='corrections'?'Correction requests':'Entry register'} sub={`${rows.length} entries · ${rows.reduce((n,e)=>n+e.items.length,0)} battery items`} action="New entry" onPress={()=>nav('new')}/><Card><Field label="Search entries" value={query} onChange={setQuery} placeholder="Reference, serial, model, or customer"/><Row style={{flexWrap:'wrap',alignItems:'flex-end'}}><Select label="Type" value={type} options={['All',...state.entryTypes]} onChange={setType}/><Select label="Status" value={status} options={['All','Draft','Pending sync','Submitted','Under Review','Approved','Rejected','Corrected','Conflict','Cancelled']} onChange={setStatus}/><Select label="Model" value={model} options={['All',...state.models.map(m=>m.id)]} onChange={setModel}/><Field label="From date" value={from} onChange={setFrom} placeholder="YYYY-MM-DD"/><Field label="To date" value={to} onChange={setTo} placeholder="YYYY-MM-DD"/></Row><Button label="Clear filters" kind="ghost" small onPress={()=>{setQuery('');setType('All');setStatus('All');setModel('All');setFrom('');setTo('');}}/></Card><Card><EntryRows entries={rows} onOpen={e=>nav(e.status==='Draft'?'draft':'entry',e.id)}/></Card></View>;
}
export function EntryDetail({id,nav}:{id:string;nav:Nav}) {
 const {state,setState,isAdmin,dealerId,canEdit,role,audit,notify}=useStore();const e=state.entries.find(e=>e.id===id&&(isAdmin||e.dealerId===dealerId));
 const [action,setAction]=useState(''),[correction,setCorrection]=useState('');
 if(!e)return <Empty title="Entry unavailable" text="This entry is not in your workspace."/>;
 function decide(reason:string) {
  if(!e||!canEdit)return;
  if(isAdmin&&state.offline){notify('Go online before making an admin decision.');return;}
  if(action==='Approve entry') {
   const errors=validateEntry(e,state);if(Object.keys(errors).length){notify(Object.values(errors)[0]);return;}
   setState(s=>audit(approveEntry(s,e),'Entry approved',e.id,reason,e.status,'Approved'));notify('Entry approved. Battery history and stock updated.');
  }else if(action==='Approve correction'){
   const next={...e,id:uid('COR'),linkedTo:e.id,status:'Corrected' as const,remarks:e.correction!.value,correction:undefined,createdAt:new Date().toISOString()};
   setState(s=>audit({...s,entries:[next,...s.entries.map(x=>x.id===e.id?{...x,correction:{...x.correction!,status:'Approved'}}:x)]},'Correction approved',e.id,reason,e.remarks,next.remarks));notify('A linked correction has been created. Original values remain available.');
  }else if(action==='Request correction'){
   if(!correction.trim()){notify('Enter the proposed corrected remarks first.');return;}
   setState(s=>audit({...s,entries:s.entries.map(x=>x.id===e.id?{...x,correction:{reason,value:correction,status:'Pending'}}:x)},'Correction requested',e.id,reason,e.remarks,correction));notify('Correction request is waiting for admin review.');
  }else if(action==='Reject correction'){
   setState(s=>audit({...s,entries:s.entries.map(x=>x.id===e.id?{...x,correction:{...x.correction!,status:'Rejected'}}:x)},action,e.id,reason));
  }else{
   const status=action==='Reject entry'?'Rejected':action==='Start review'?'Under Review':'Cancelled';
   setState(s=>audit({...s,entries:s.entries.map(x=>x.id===e.id?{...x,status}:x)},action,e.id,reason,e.status,status));notify(`${e.id}: ${status}`);
  }
 }
 return <View style={{gap:20}}><SectionTitle title={e.id} sub={`${e.type} · ${dateLabel(e.date)}`} action="Back to register" onPress={()=>nav('activity')}/><Card><Row style={{justifyContent:'space-between',flexWrap:'wrap'}}><Badge status={e.status}/><Button label="Print / PDF acknowledgement" icon="download" kind="secondary" onPress={()=>printEntry(e,state.dealers.find(d=>d.id===e.dealerId)!).catch(()=>notify('Printing is unavailable on this device.'))}/></Row><View style={s.divider}/><Row style={{flexWrap:'wrap'}}><KeyValue label="Dealer" value={state.dealers.find(d=>d.id===e.dealerId)?.name}/><KeyValue label="Customer" value={e.customer}/><KeyValue label="Location" value={e.place}/><KeyValue label="Items / total quantity" value={String(e.items.length)}/></Row><KeyValue label="Reference / order" value={e.order}/><KeyValue label="Dealer remarks" value={e.remarks}/>{e.linkedTo&&<Button label={`Original entry: ${e.linkedTo}`} kind="ghost" onPress={()=>nav('entry',e.linkedTo)}/>}</Card>
 {e.items.map((it,i)=><Card key={it.id}><SectionTitle title={`Battery ${i+1} · ${it.model}`} sub={it.id}/><Row style={{flexWrap:'wrap'}}><KeyValue label="Battery code" value={it.code}/><KeyValue label="Serial" value={it.serial}/><KeyValue label="Old battery code" value={it.oldSerial}/><KeyValue label="Manufactured" value={it.mfg}/><KeyValue label="Replacement month" value={it.rpl}/><KeyValue label="Return month" value={it.rtn}/><KeyValue label="Warranty / Rpl reference" value={it.wr}/></Row><KeyValue label="Item remarks" value={it.remarks}/><Row style={{flexWrap:'wrap'}}><Button label="Battery & chain" icon="link" kind="secondary" onPress={()=>nav('battery',it.code)}/>{it.oldSerial&&!state.batteries.some(b=>b.code===it.oldSerial)&&<Badge status="Old serial not on record"/>}</Row></Card>)}
 <Card><SectionTitle title="Evidence & capture"/><Row style={{flexWrap:'wrap'}}>{e.evidence.map((uri,i)=><Image key={i} source={{uri}} style={{width:150,height:120,borderRadius:10}}/>)}</Row>{!e.evidence.length&&<Txt style={s.caption}>No photos were attached.</Txt>}<KeyValue label="GPS and capture time" value={e.gps}/><KeyValue label="Customer acknowledgement" value={e.signature?'Signature captured at submission':'Not provided'}/></Card>
 {isAdmin&&canEdit&&['Submitted','Under Review','Conflict'].includes(e.status)&&<Card><SectionTitle title="Review decision"/><Banner text="Check old and new serials, warranty eligibility, and supporting evidence before approving. An approval updates stock and the replacement chain."/><Row style={{flexWrap:'wrap'}}><Button label="Approve entry" icon="check" onPress={()=>setAction('Approve entry')}/><Button label="Start review" kind="secondary" onPress={()=>setAction('Start review')}/><Button label="Reject entry" kind="danger" onPress={()=>setAction('Reject entry')}/></Row></Card>}
 {e.correction&&<Card><SectionTitle title="Correction request"/><Badge status={e.correction.status}/><KeyValue label="Requested change to remarks" value={e.correction.value}/><KeyValue label="Reason" value={e.correction.reason}/>{isAdmin&&canEdit&&e.correction.status==='Pending'&&<Row><Button label="Approve correction" onPress={()=>setAction('Approve correction')}/><Button label="Reject correction" kind="danger" onPress={()=>setAction('Reject correction')}/></Row>}</Card>}
 {canEdit&&!['Draft','Pending sync','Cancelled'].includes(e.status)&&<Card><SectionTitle title="Corrections & retention"/><Field label="Proposed corrected remarks" value={correction} onChange={setCorrection} multiline/><Row style={{flexWrap:'wrap'}}><Button label="Request correction" kind="secondary" onPress={()=>setAction('Request correction')}/>{isAdmin&&<Button label="Void / archive entry" kind="danger" onPress={()=>setAction('Void / archive entry')}/>}</Row></Card>}
 {e.type==='Replacement'&&e.status==='Approved'&&<Button label="Handover & old battery return" icon="truck" onPress={()=>nav('returns',e.id)}/>}
 <Card><SectionTitle title="Audit trail" sub="Original records and decisions are retained."/>{state.audits.filter(a=>a.ref===e.id).map(a=><View key={a.id} style={{borderLeftWidth:2,borderColor:C.gold,padding:15,marginBottom:10}}><Txt style={{fontWeight:'600',fontSize:13}}>{a.action}</Txt><Txt style={s.caption}>{a.actor} · {new Date(a.at).toLocaleString('en-IN')}</Txt><Txt style={{fontSize:12,marginTop:6}}>{a.reason}</Txt>{a.before&&<Txt style={s.caption}>{a.before} → {a.after}</Txt>}</View>)}</Card><ReasonDialog title={action} open={!!action} onClose={()=>setAction('')} onConfirm={decide}/></View>;
}
export function Search({nav,initial=''}:{nav:Nav;initial?:string}) {
 const {state,isAdmin,dealerId}=useStore();const [query,setQuery]=useState(initial),[model,setModel]=useState('All');const q=query.toLowerCase();
 const batteries=state.batteries.filter(b=>(isAdmin||b.dealerId===dealerId)&&(model==='All'||b.model===model)&&[b.code,b.serial,b.oldSerial||'',b.model,b.customer,state.dealers.find(d=>d.id===b.dealerId)?.name||''].some(v=>v.toLowerCase().includes(q)));
 return <View style={{gap:20}}><SectionTitle title="Find the whole story" sub="Search a code, serial, customer, or dealer to trace a battery’s lifecycle."/><Card><Field label="Universal search" value={query} onChange={setQuery} placeholder="Try 0047, M5, or Suresh Transport"/><Select label="Battery model" value={model} options={['All',...state.models.map(m=>m.id)]} onChange={setModel}/></Card><Txt style={s.caption}>{batteries.length} matching batteries</Txt>{batteries.length?batteries.map(b=><Pressable key={b.code} accessibilityRole="button" accessibilityLabel={`Battery ${b.code}`} onPress={()=>nav('battery',b.code)}><Card><Row><View style={{backgroundColor:C.goldSoft,padding:14,borderRadius:12}}><Icon name="battery-charging" color={C.ink}/></View><View style={{flex:1,gap:7}}><Txt style={{fontWeight:'600'}}>{b.code} <Txt style={s.caption}>· {b.model}</Txt></Txt><Txt style={s.caption}>Serial {b.serial} · {b.customer||'Unassigned'} · {state.dealers.find(d=>d.id===b.dealerId)?.city}</Txt></View><Badge status={warranty(b).status}/><Icon name="chevron-right"/></Row></Card></Pressable>):<Empty title="No matching batteries" text="Try a different serial or a shorter code. Only batteries in your workspace are shown."/>}</View>;
}
export function BatteryDetail({id,nav}:{id:string;nav:Nav}) {
 const {state,setState,isAdmin,dealerId,canEdit,notify,audit}=useStore();const [override,setOverride]=useState(false),[days,setDays]=useState('14');
 const b=state.batteries.find(b=>b.code===id&&(isAdmin||b.dealerId===dealerId));if(!b)return <Card><Empty title="Battery not on record" text="This serial has not entered the approved registry yet."/><Button label="Back to search" onPress={()=>nav('search')}/></Card>;
 const w=warranty(b),chain=chainFor(b.code,state.batteries.filter(b=>isAdmin||b.dealerId===dealerId));
 return <View style={{gap:20}}><SectionTitle title={`${b.model} · ${b.code}`} sub={`Serial ${b.serial} · ${b.customer||'Available stock'}`} action="Back to search" onPress={()=>nav('search')}/><Card><Row style={{justifyContent:'space-between'}}><SectionTitle title="Warranty at a glance"/><Badge status={w.status}/></Row><Txt style={{fontSize:36,fontWeight:'600'}}>{b.expiry?w.days:'—'} <Txt style={{fontSize:14,color:C.muted}}>days of cover remaining</Txt></Txt><View style={{height:7,backgroundColor:C.line,borderRadius:5,marginVertical:22}}><View style={{height:7,width:`${w.progress*100}%`,backgroundColor:C.green,borderRadius:5}}/></View><Row style={{flexWrap:'wrap'}}><KeyValue label="Original warranty start" value={dateLabel(b.start)}/><KeyValue label="Expiry date" value={dateLabel(b.expiry)}/><KeyValue label="Policy version" value={b.policy}/><KeyValue label="Custody / status" value={b.state}/></Row><Banner text="A replacement carries forward the original warranty dates and policy. It does not restart the warranty term."/>{canEdit&&<Row style={{flexWrap:'wrap'}}><Button label="Start replacement claim" icon="refresh-cw" onPress={()=>nav('claim',b.code)}/><Button label="Request warranty override" kind="secondary" onPress={()=>setOverride(true)}/></Row>}</Card>
 <Card><SectionTitle title="Replacement chain" sub={`${Math.max(0,chain.length-1)} replacement(s) · traceable in both directions`}/>{chain.length>3&&<Banner tone="warning" text="More than two replacements in this chain. Review for recurring failures."/>}{chain.map((c,i)=><Pressable key={c.code} onPress={()=>nav('battery',c.code)} accessibilityRole="button"><Row style={{alignItems:'flex-start',marginBottom:22}}><View style={{width:32,height:32,borderRadius:16,backgroundColor:c.code===id?C.gold:C.bg,alignItems:'center',justifyContent:'center'}}><Txt style={{fontSize:12}}>{i+1}</Txt></View><View style={{flex:1,gap:7}}><Txt style={{fontWeight:'600'}}>{c.code} · {c.model}</Txt><Txt style={s.caption}>{i===0?'Original sale reference':'Replacement · warranty inherited'} · {c.customer}</Txt><Badge status={c.state}/></View><Icon name="arrow-up-right"/></Row></Pressable>)}</Card><Card><SectionTitle title="Related entries"/><EntryRows entries={state.entries.filter(e=>(isAdmin||e.dealerId===dealerId)&&e.items.some(i=>i.code===b.code||i.oldSerial===b.code))} onOpen={e=>nav('entry',e.id)}/></Card><ReasonDialog title="Request warranty override" open={override} onClose={()=>setOverride(false)} extra={<Field label="Extension days" value={days} onChange={setDays} numeric/>} onConfirm={reason=>{if(!/^\d+$/.test(days)||Number(days)<1){notify('Enter a positive whole number of days.');return;}setState(s=>audit({...s,overrides:[{id:uid('OVR'),code:b.code,days:Number(days),reason,status:'Pending'},...s.overrides]},'Warranty override requested',b.code,reason));notify('Override request added to the admin queue.');}}/></View>;
}
export function SyncCentre({nav}:{nav:Nav}) {
 const {state,setState,dealerId,isAdmin,notify,audit}=useStore();const rows=state.entries.filter(e=>(isAdmin||e.dealerId===dealerId)&&['Pending sync','Conflict'].includes(e.status));
 const sync=()=>{if(state.offline){notify('Switch off offline mode to retry syncing.');return;}setState(s=>{let entries=[...s.entries];for(const e of rows){if(e.status==='Conflict')continue;const errors=validateEntry(e,s);const active=s.dealers.find(d=>d.id===e.dealerId)?.status==='Active';entries=entries.map(x=>x.id===e.id?{...x,status:active&&!Object.keys(errors).length?'Submitted':'Conflict',retries:x.retries+1}:x);}return audit({...s,entries,lastSync:new Date().toISOString()},'Local queue reconciled','SYNC','Demo adapter checked validation and dealer status.');});notify('Queue checked. Valid entries submitted; conflicts preserved for review.');};
 return <View style={{gap:20}}><SectionTitle title="Sync centre" sub="Your field work stays with you, even without a signal."/><Card><Row style={{justifyContent:'space-between',flexWrap:'wrap'}}><Badge status={state.offline?'Offline':'Online'}/><Button label={state.offline?'Go online':'Simulate offline'} kind="secondary" onPress={()=>setState(s=>({...s,offline:!s.offline}))}/></Row><KeyValue label="Last successful local sync" value={new Date(state.lastSync).toLocaleString('en-IN')}/><Banner text="This frontend uses a local sync adapter. Queued records persist across reloads; connecting a backend will enable actual server reconciliation."/><Button label="Retry sync" icon="refresh-cw" onPress={sync}/></Card>{rows.map(e=><Card key={e.id}><SectionTitle title={e.id} sub={`${e.items.length} items · ${e.retries} retry attempts`}/><Badge status={e.status}/>{e.status==='Conflict'&&<View style={{marginTop:16}}><Banner tone="warning" text={Object.values(validateEntry(e,state))[0]||'Serial custody changed after capture. Open this entry and request a correction or admin review.'}/><Button label="Resolve conflict" kind="secondary" onPress={()=>nav('entry',e.id)}/></View>}</Card>)}{!rows.length&&<Empty title="All caught up" text="There are no pending records on this device."/>}</View>;
}

