import React, { useRef, useState } from 'react';
import { View, Image, PanResponder } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as ImagePicker from 'expo-image-picker';
import * as Location from 'expo-location';
import Svg, { Path } from 'react-native-svg';
import { C, Txt, Row, Button, Field, Banner, Dialog } from './ui';
import { useStore } from './store';
export function Scanner({onCode,onClose}:{onCode:(code:string)=>void;onClose:()=>void}) {
 const [permission,requestPermission]=useCameraPermissions();const [manual,setManual]=useState(''),[scanned,setScanned]=useState(false);
 return <Dialog open title="Capture a battery serial" onClose={onClose}><Banner text="Scan a QR code or barcode, then review the captured value. Manual entry is always available."/>{permission?.granted?<View style={{height:230,borderRadius:12,overflow:'hidden',marginBottom:18}}><CameraView style={{flex:1}} barcodeScannerSettings={{barcodeTypes:['qr','code128','code39','ean13','ean8']}} onBarcodeScanned={scanned?undefined:({data})=>{setManual(data);setScanned(true);}}/></View>:<Button label="Enable camera" icon="camera" kind="secondary" onPress={()=>{requestPermission().catch(()=>{});}}/>}<View style={{marginTop:18}}><Field label="Battery code" value={manual} onChange={setManual} numeric placeholder="e.g. 26080311"/></View><Row style={{justifyContent:'flex-end'}}>{scanned&&<Button label="Scan again" kind="secondary" onPress={()=>setScanned(false)}/>}<Button label="Use this code" disabled={!manual.trim()} onPress={()=>{onCode(manual.trim());onClose();}}/></Row></Dialog>;
}
export function Signature({value,onChange}:{value:string;onChange:(v:string)=>void}) {
 const [paths,setPaths]=useState<string[]>(value?JSON.parse(value):[]);const current=useRef('');const pathsRef=useRef(paths);const onChangeRef=useRef(onChange);onChangeRef.current=onChange;
 const pan=useRef(PanResponder.create({onStartShouldSetPanResponder:()=>true,onMoveShouldSetPanResponder:()=>true,onPanResponderGrant:e=>{current.current=`M ${e.nativeEvent.locationX} ${e.nativeEvent.locationY}`;setPaths([...pathsRef.current,current.current]);},onPanResponderMove:e=>{current.current+=` L ${e.nativeEvent.locationX} ${e.nativeEvent.locationY}`;setPaths([...pathsRef.current,current.current]);},onPanResponderRelease:()=>{pathsRef.current=[...pathsRef.current,current.current];setPaths(pathsRef.current);onChangeRef.current(JSON.stringify(pathsRef.current));}})).current;
 return <View><Txt style={{fontSize:11,color:C.muted,marginBottom:8}}>Customer acknowledgement · draw below (optional)</Txt><View {...pan.panHandlers} style={{height:130,backgroundColor:'#FAFBFD',borderWidth:1,borderColor:C.line,borderRadius:10,touchAction:'none'} as any}><Svg width="100%" height="130">{paths.map((p,i)=><Path key={i} d={p} stroke={C.ink} strokeWidth={2} fill="none"/>)}</Svg></View><Button label="Clear signature" kind="ghost" small onPress={()=>{setPaths([]);pathsRef.current=[];onChange('');}}/></View>;
}
export function Evidence({photos,gps,signature,onPhotos,onGps,onSignature}:{photos:string[];gps?:string;signature?:string;onPhotos:(p:string[])=>void;onGps:(v:string)=>void;onSignature:(v:string)=>void}) {
 const {notify}=useStore();
 async function photo(camera=false){try{if(camera){const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){notify('Camera access declined. You can attach a photo from your library.');return;}}const result=await (camera?ImagePicker.launchCameraAsync:ImagePicker.launchImageLibraryAsync)({mediaTypes:['images'],quality:.5,base64:true});if(!result.canceled){const a=result.assets[0];onPhotos([...photos,a.base64?`data:image/jpeg;base64,${a.base64}`:a.uri]);}}catch{notify('Photo capture is unavailable. Try choosing a photo from your library.');}}
 async function locate(){try{const p=await Location.requestForegroundPermissionsAsync();if(!p.granted){notify('Location declined. You can continue without GPS.');return;}const l=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});onGps(`${l.coords.latitude.toFixed(5)}, ${l.coords.longitude.toFixed(5)} · ±${Math.round(l.coords.accuracy||0)}m · ${new Date().toISOString()}`);}catch{notify('Location is unavailable. Your entry can continue without it.');}}
 return <View style={{gap:16}}><Row style={{flexWrap:'wrap'}}><Button label="Take photo" icon="camera" kind="secondary" onPress={()=>photo(true)}/><Button label="Attach photo" icon="image" kind="secondary" onPress={()=>photo()}/><Button label={gps?'Location attached':'Add GPS'} icon="map-pin" kind="secondary" onPress={locate}/></Row>{photos.length>0&&<Row style={{flexWrap:'wrap'}}>{photos.map((p,i)=><View key={i}><Image source={{uri:p}} style={{width:100,height:90,borderRadius:8}}/><Button label={`Remove photo ${i+1}`} kind="ghost" small onPress={()=>onPhotos(photos.filter((_,j)=>i!==j))}/></View>)}</Row>}{gps&&<Txt style={{fontSize:11,color:C.green}}>{gps}</Txt>}<Signature value={signature||''} onChange={onSignature}/><Banner text="Label photos are retained as evidence. Automated OCR needs a connected recognition service; confirm label values manually in this frontend."/></View>;
}
