import React from 'react';
import { View, Pressable, useWindowDimensions } from 'react-native';
import { useStore } from './store';
import { C, s, Txt, Row, Card, Icon, Button, Badge, SectionTitle, BatteryArt, IconName } from './ui';
import { Entry, dateLabel, warranty } from './domain';
export type Nav=(route:string,id?:string)=>void;
export function EntryRows({entries,onOpen}:{entries:Entry[];onOpen:(e:Entry)=>void}) {
 const wide=useWindowDimensions().width>800;
 if(!entries.length)return <Txt style={{padding:24,color:C.muted}}>No entries match these filters.</Txt>;
 return <View>{wide&&<Row style={{paddingVertical:12,paddingHorizontal:18,backgroundColor:'#FAFBFC',borderTopWidth:1,borderBottomWidth:1,borderColor:C.line}}>{['ENTRY / BATTERY','TYPE','DATE','STATUS',''].map((h,i)=><Txt key={i} style={{fontSize:9,letterSpacing:.9,color:C.muted,fontWeight:'600',flex:i===0?2:i===4?.25:1}}>{h}</Txt>)}</Row>}{entries.map((e,i)=><Pressable key={e.id} accessibilityRole="button" accessibilityLabel={`Open ${e.id}`} onPress={()=>onOpen(e)} style={({hovered}:any)=>({paddingHorizontal:wide?18:0,paddingVertical:17,borderBottomWidth:i<entries.length-1?1:0,borderColor:C.line,backgroundColor:hovered?'#FAFBFC':'transparent'})}>{wide?<Row><View style={{flex:2,gap:5}}><Txt style={{fontSize:12,fontWeight:'600'}}>{e.id}</Txt><Txt style={{fontSize:10,color:C.muted}}>{e.items[0]?.model} · {e.items[0]?.code}{e.items.length>1?`  +${e.items.length-1} more`:''}</Txt></View><Txt style={{fontSize:11,flex:1}} numberOfLines={2}>{e.type}</Txt><Txt style={{fontSize:11,color:C.muted,flex:1}}>{dateLabel(e.date).replace(' 2026','')}</Txt><View style={{flex:1}}><Badge status={e.status}/></View><View style={{flex:.25,alignItems:'flex-end'}}><Icon name="chevron-right" size={15}/></View></Row>:<View style={{gap:9}}><Row style={{justifyContent:'space-between'}}><Txt style={{fontWeight:'600',fontSize:12}}>{e.id}</Txt><Badge status={e.status}/></Row><Row style={{justifyContent:'space-between'}}><Txt style={s.caption}>{e.items[0]?.model} · {e.items[0]?.code}</Txt><Txt style={s.caption}>{e.type}</Txt></Row></View>}</Pressable>)}</View>;
}
export function Dashboard({nav}:{nav:Nav}) {
 const {state,dealerId,isAdmin,canEdit}=useStore();const width=useWindowDimensions().width;const wide=width>1120;
 const dealer=state.dealers.find(d=>d.id===dealerId)!;
 const entries=state.entries.filter(e=>isAdmin||e.dealerId===dealerId);
 const batteries=state.batteries.filter(b=>isAdmin||b.dealerId===dealerId);
 const pending=entries.filter(e=>['Submitted','Under Review','Conflict'].includes(e.status));
 const metrics:[string,number,IconName,string][]=[isAdmin?['Active dealers',state.dealers.filter(d=>d.status==='Active').length,'users','Across your network']:['Total batteries',batteries.length,'battery-charging','In your battery register'],['Replacements',entries.filter(e=>e.type==='Replacement').length,'refresh-cw','A continuous service journey'],['This month',entries.filter(e=>e.date.startsWith(new Date().toISOString().slice(0,7))).length,'bar-chart-2','Entries recorded this month'],['Needs review',pending.length,'clock','Awaiting the next step']];
 const monthly=Array.from({length:7},(_,i)=>{const day=new Date();day.setDate(day.getDate()-6+i);const key=day.toISOString().slice(0,10);return {label:day.toLocaleDateString('en',{weekday:'short'}),count:entries.filter(e=>e.date===key).length};}); const max=Math.max(3,...monthly.map(d=>d.count));
 return <View style={{gap:24}}>
  <Row style={{justifyContent:'space-between',alignItems:'flex-start',flexWrap:'wrap'}}><View style={{gap:8}}><Row><View style={{width:6,height:6,borderRadius:4,backgroundColor:C.gold}}/><Txt style={{fontSize:10,letterSpacing:1.8,color:C.muted}}>YOUR DAILY POWER CHECK</Txt></Row><Txt style={{fontSize:width<500?25:30,fontWeight:'600',letterSpacing:-1}}>{isAdmin?'Your network, at a glance.':'Good morning, Rahul'}{!isAdmin&&<Txt style={{fontSize:26}}> ☀</Txt>}</Txt><Txt style={s.caption}>{isAdmin?'A clear view of every dealer, battery, and decision.':"Let’s keep your business powered. Here’s what’s happening today."}</Txt></View><Row style={{backgroundColor:'white',borderWidth:1,borderColor:C.line,borderRadius:8,paddingHorizontal:13,paddingVertical:11}}><Icon name="calendar" size={14}/><Txt style={{fontSize:11}}>{new Date().toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short',year:'numeric'})}</Txt></Row></Row>
  <View style={[s.grid,{gap:15}]}>{metrics.map(([label,value,icon,sub],i)=><Card key={label} style={{flex:1,minWidth:width<600?'44%':170,padding:19}}><Row style={{justifyContent:'space-between',marginBottom:16}}><Txt style={{fontSize:11,color:C.muted}}>{label}</Txt><View style={{padding:8,borderRadius:8,backgroundColor:i===3?C.goldSoft:'#F2F5F7'}}><Icon name={icon} size={16} color={i===3?'#B68524':C.ink}/></View></Row><Txt style={{fontSize:32,fontWeight:'600',letterSpacing:-1}}>{String(value).padStart(2,'0')}</Txt><Txt style={{fontSize:10,color:i===3?'#A87925':C.muted,marginTop:10}}>{sub}</Txt></Card>)}</View>
  <View style={{flexDirection:wide?'row':'column',gap:22}}><View style={{flex:1.95,gap:22}}>
   <View style={{backgroundColor:C.nav,borderRadius:15,minHeight:217,overflow:'hidden',padding:27,justifyContent:'center'}}><View style={{position:'absolute',right:wide?5:0,top:5,opacity:width<500?.22:1}}><BatteryArt size={258}/></View><View style={{gap:12,maxWidth:'75%'}}><Txt style={{fontSize:9,letterSpacing:2,color:'#D6AD59'}}>BUILT TO KEEP YOU MOVING</Txt><Txt style={{fontSize:25,fontWeight:'600',color:'white',lineHeight:33,letterSpacing:-.5}}>Every battery.{'\n'}A better service experience.</Txt><Txt style={{color:'#A8B3BC',fontSize:11,lineHeight:18,maxWidth:300}}>Record a replacement in minutes.{'\n'}We’ll keep the history connected.</Txt><Row style={{marginTop:5}}><Button label={isAdmin?'Review requests':'New replacement'} icon={isAdmin?'check-circle':'plus'} disabled={!canEdit} onPress={()=>nav(isAdmin?'approvals':'new','Replacement')}/></Row></View></View>
   <Card style={{padding:0,overflow:'hidden'}}><View style={{paddingHorizontal:22,paddingTop:20}}><SectionTitle title="Recent entries" sub="The latest from your battery register" action="View all" onPress={()=>nav('activity')}/></View><View style={!wide?{paddingHorizontal:18}:undefined}><EntryRows entries={entries.slice(0,5)} onOpen={e=>nav('entry',e.id)}/></View><Row style={{padding:15,justifyContent:'center',backgroundColor:'#FCFCFD'}}><Icon name="shield" size={12} color={C.green}/><Txt style={{fontSize:10,color:C.muted}}>Every entry is saved with a complete audit trail</Txt></Row></Card>
  </View><View style={{flex:1,minWidth:wide?285:undefined,gap:22}}>
   <Card><SectionTitle title="Quick actions"/><View style={{flexDirection:'row',justifyContent:'space-between',gap:10}}>{([['maximize','Scan battery','scan'],['search','Find a serial','search'],['package','My stock','stock']] as [IconName,string,string][]).map(([icon,label,route])=><Pressable accessibilityRole="button" accessibilityLabel={label} onPress={()=>nav(route)} key={label} style={{flex:1,alignItems:'center',gap:11,paddingVertical:7}}><View style={{width:48,height:48,backgroundColor:'#F5F6F8',borderRadius:13,alignItems:'center',justifyContent:'center'}}><Icon name={icon} size={20} color={C.ink}/></View><Txt style={{fontSize:10,textAlign:'center'}}>{label}</Txt></Pressable>)}</View></Card>
   <Card><SectionTitle title="Needs your attention"/><View style={{gap:17}}>{([{icon:'alert-circle',color:'#AE7A1E',bg:C.goldSoft,title:`${pending.length} entries need a review`,sub:'Keep your records moving',route:isAdmin?'approvals':'activity'},{icon:'shield',color:C.blue,bg:C.blueSoft,title:`${batteries.filter(b=>warranty(b).status==='Expiring soon').length} warranties expiring soon`,sub:'A good time to check in',route:'warranty'},{icon:'package',color:C.purple,bg:'#F2EEFA',title:'M5 stock is running low',sub:'3 available · reorder level 5',route:'stock'}] as {icon:IconName;color:string;bg:string;title:string;sub:string;route:string}[]).map(a=><Pressable key={a.title} accessibilityRole="button" onPress={()=>nav(a.route)}><Row><View style={{padding:10,backgroundColor:a.bg,borderRadius:9}}><Icon name={a.icon} size={17} color={a.color}/></View><View style={{flex:1,gap:5}}><Txt style={{fontSize:11,fontWeight:'600'}}>{a.title}</Txt><Txt style={{fontSize:10,color:C.muted}}>{a.sub}</Txt></View><Icon name="chevron-right" size={13}/></Row></Pressable>)}</View></Card>
   <Card><SectionTitle title="This week’s activity" sub={`${monthly.reduce((t,d)=>t+d.count,0)} entries in the last 7 days`}/><Row style={{alignItems:'flex-end',justifyContent:'space-between',height:120,gap:14}}>{monthly.map((d,i)=><View key={i} style={{flex:1,alignItems:'center',gap:9}}><Txt style={{fontSize:9,color:C.muted}}>{d.count}</Txt><View style={{width:'100%',maxWidth:24,height:Math.max(4,d.count/max*75),backgroundColor:i===6?C.gold:'#E6EBEF',borderRadius:4}}/><Txt style={{fontSize:9,color:C.muted}}>{d.label}</Txt></View>)}</Row></Card>
  </View></View>
  <Row style={{justifyContent:'space-between',paddingVertical:2,flexWrap:'wrap'}}><Txt style={{fontSize:10,color:'#949DA6'}}>FELIX BATTERIES INDUSTRIES  /  POWERING RELATIONSHIPS</Txt><Row><View style={{width:5,height:5,borderRadius:3,backgroundColor:C.green}}/><Txt style={{fontSize:10,color:C.muted}}>{isAdmin?'Network workspace':`${dealer.name} · ${dealer.id}`}</Txt></Row></Row>
 </View>;
}
