import React, { useState } from 'react';
import { View, Pressable } from 'react-native';
import { useStore } from './store';
import { C,s,Card,Row,Txt,Badge,Button,SectionTitle,Field,Select,Dialog,ReasonDialog,Banner,Empty,KeyValue,Icon } from './ui';
import { Nav } from './Dashboard';
import { uid,today } from './domain';
export function Inventory({nav}:{nav:Nav}) {
 const {state,setState,isAdmin,dealerId,canEdit,audit,notify}=useStore();const [tab,setTab]=useState('Stock overview'),[model,setModel]=useState('All'),[status,setStatus]=useState('All'),[movement,setMovement]=useState(false),[code,setCode]=useState(''),[to,setTo]=useState('Available'),[target,setTarget]=useState(dealerId),[reason,setReason]=useState('');
 const batteries=state.batteries.filter(b=>(isAdmin||b.dealerId===dealerId)&&(model==='All'||b.model===model)&&(status==='All'||b.state===status));
 function move(){const b=state.batteries.find(b=>b.code===code&&(isAdmin||b.dealerId===dealerId));if(!b){notify('Choose a battery code in your stock register.');return;}if(!reason.trim()){notify('A stock movement needs a reason.');return;}if(b.state==='Scrap'){notify('Scrap is a terminal state. Record an admin correction instead.');return;}if(b.state===to&&b.dealerId===target){notify('Choose a different stock state or destination.');return;}const transitions:Record<string,string[]>={Available:['Allocated','Sold','Repair','Damaged','Scrap'],Allocated:['Available','Sold','Returned'],Sold:['Returned','Repair'],Returned:['Repair','Available','Damaged','Scrap'],Replacement:['Returned','Repair'],Repair:['Available','Returned','Damaged','Scrap'],Damaged:['Repair','Scrap']};if(!transitions[b.state]?.includes(to)&&b.dealerId===target){notify(`A ${b.state} battery cannot move directly to ${to}.`);return;}setState(s=>audit({...s,batteries:s.batteries.map(x=>x.code===code?{...x,state:to,dealerId:isAdmin?target:dealerId}:x),movements:[{id:uid('MOV'),code,model:b.model,dealerId:isAdmin?target:dealerId,from:b.state,to,reason,date:today()},...s.movements]},'Stock movement',code,reason,`${b.dealerId} / ${b.state}`,`${target} / ${to}`));setMovement(false);notify('Movement posted to the stock ledger.');}
 return <View style={{gap:20}}><SectionTitle title={isAdmin?'Inventory & custody':'Your stock, in view'} sub="Serial-level movements. A clear picture of what is on hand."/>{canEdit&&<Row><Button label="Record stock movement" icon="plus" onPress={()=>setMovement(true)}/></Row>}<Row style={{flexWrap:'wrap'}}>{['Stock overview','Movement ledger','Low-stock alerts'].map(t=><Button key={t} label={t} kind={tab===t?'primary':'secondary'} onPress={()=>setTab(t)}/>)}</Row><Row style={{flexWrap:'wrap'}}><Select label="Model filter" value={model} options={['All',...state.models.map(m=>m.id)]} onChange={setModel}/><Select label="Stock status" value={status} options={['All','Available','Allocated','Sold','Returned','Replacement','Repair','Damaged','Scrap']} onChange={setStatus}/></Row>
 {tab==='Stock overview'&&<><View style={s.grid}>{state.models.filter(m=>model==='All'||m.id===model).map(m=>{const count=batteries.filter(b=>b.model===m.id&&b.state==='Available').length;return <Card key={m.id} style={{minWidth:140,flex:1}}><Row style={{justifyContent:'space-between'}}><Txt style={s.title}>{m.id}</Txt><Icon name="battery" color={C.ink}/></Row><Txt style={{fontSize:30,marginVertical:10}}>{count}</Txt><Txt style={s.caption}>available · {m.capacity}</Txt>{count<m.threshold&&<View style={{marginTop:10}}><Badge status="Low stock"/></View>}</Card>;})}</View><Card><SectionTitle title={`${batteries.length} batteries`}/>{batteries.map(b=><Pressable key={b.code} onPress={()=>nav('battery',b.code)} accessibilityRole="button" style={{paddingVertical:16,borderBottomWidth:1,borderColor:C.line}}><Row style={{justifyContent:'space-between'}}><View style={{gap:5}}><Txt style={{fontSize:13,fontWeight:'600'}}>{b.model} · {b.code}</Txt><Txt style={s.caption}>{b.dealerId} · Serial {b.serial}</Txt></View><Badge status={b.state}/><Icon name="chevron-right" size={16}/></Row></Pressable>)}</Card></>}
 {tab==='Movement ledger'&&<Card><SectionTitle title="Movement ledger" sub="Posted movements are retained. Corrections use a new movement."/>{state.movements.filter(m=>(isAdmin||m.dealerId===dealerId)&&(model==='All'||m.model===model)&&(status==='All'||m.to===status)).map(m=><View key={m.id} style={{paddingVertical:16,borderBottomWidth:1,borderColor:C.line}}><Row style={{justifyContent:'space-between'}}><Txt style={{fontWeight:'600',fontSize:13}}>{m.code} · {m.model}</Txt><Txt style={s.caption}>{m.date}</Txt></Row><Txt style={{marginVertical:7,fontSize:12}}>{m.from} → {m.to} · {m.dealerId}</Txt><Txt style={s.caption}>{m.reason}</Txt></View>)}</Card>}
 {tab==='Low-stock alerts'&&state.models.filter(m=>batteries.filter(b=>b.model===m.id&&b.state==='Available').length<m.threshold).map(m=><Card key={m.id}><SectionTitle title={`${m.id} needs a stock review`}/><Badge status="Low stock"/><KeyValue label="Reorder threshold" value={`${m.threshold} batteries`}/>{isAdmin&&canEdit&&<Field label={`${m.id} threshold`} numeric value={String(m.threshold)} onChange={v=>{if(/^\d+$/.test(v))setState(s=>audit({...s,models:s.models.map(x=>x.id===m.id?{...x,threshold:Number(v)}:x)},'Threshold changed',m.id,'Reorder threshold updated',String(m.threshold),v));}}/>}</Card>)}
 <Dialog title="Record stock movement" open={movement} onClose={()=>setMovement(false)}><Field label="Battery code *" value={code} onChange={setCode} numeric/><Select label="Destination state" value={to} options={['Available','Allocated','Sold','Returned','Repair','Damaged','Scrap']} onChange={setTo}/>{isAdmin&&<Select label="Destination dealer" value={target} options={state.dealers.filter(d=>d.status==='Active').map(d=>d.id)} onChange={setTarget}/>}<Field label="Movement reason *" value={reason} onChange={setReason} multiline/><Button label="Post movement" onPress={move}/></Dialog></View>;
}
export function Returns({nav,id}:{nav:Nav;id?:string}) {
 const {state,setState,isAdmin,dealerId,canEdit,audit,notify}=useStore();const [action,setAction]=useState<{id:string;title:string}|null>(null);
 const entries=state.entries.filter(e=>(isAdmin||e.dealerId===dealerId)&&e.type==='Replacement'&&e.status==='Approved'&&(!id||e.id===id));
 const stages=['At dealer','In transit','Received','Testing','Repaired','Scrapped','Closed'];
 return <View style={{gap:20}}><SectionTitle title="Handover & returns" sub="Track the replacement out, and the old battery back."/>{entries.map(e=>{const current=e.returnState||'At dealer';return <Card key={e.id}><SectionTitle title={e.id} sub={`${e.customer} · ${e.items.map(i=>i.oldSerial).join(', ')}`}/><Badge status={current}/><KeyValue label="Customer handover" value={e.handover||'Awaiting handover confirmation'}/><KeyValue label="Latest return details" value={e.returnNote}/><View style={{gap:15,marginVertical:18}}>{stages.filter(stage=>stage!=='Scrapped'||current==='Scrapped').map((stage,i)=><Row key={stage}><View style={{width:26,height:26,borderRadius:13,backgroundColor:stages.indexOf(current)>=stages.indexOf(stage)?C.greenSoft:C.bg,justifyContent:'center',alignItems:'center'}}><Icon name={stages.indexOf(current)>=stages.indexOf(stage)?'check':'circle'} size={13} color={C.green}/></View><Txt style={{fontSize:12,color:stage===current?C.ink:C.muted}}>{stage}</Txt></Row>)}</View>{canEdit&&<Row style={{flexWrap:'wrap'}}>{!e.handover&&<Button label="Confirm customer handover" onPress={()=>setAction({id:e.id,title:'Confirm handover'})}/>} {current==='At dealer'&&e.handover&&<Button label="Dispatch old battery" kind="secondary" onPress={()=>setAction({id:e.id,title:'In transit'})}/>} {isAdmin&&current==='In transit'&&<Button label="Confirm receipt" onPress={()=>setAction({id:e.id,title:'Received'})}/>} {isAdmin&&current==='Received'&&<Button label="Send for testing" onPress={()=>setAction({id:e.id,title:'Testing'})}/>} {isAdmin&&current==='Testing'&&<><Button label="Mark repaired" onPress={()=>setAction({id:e.id,title:'Repaired'})}/><Button label="Mark scrapped" kind="danger" onPress={()=>setAction({id:e.id,title:'Scrapped'})}/></>}{isAdmin&&['Repaired','Scrapped'].includes(current)&&<Button label="Close return" onPress={()=>setAction({id:e.id,title:'Closed'})}/>}<Button label="Entry details" kind="ghost" onPress={()=>nav('entry',e.id)}/></Row>}</Card>;})}{!entries.length&&<Empty title="No approved replacements to track" text="Approved replacements appear here for handover and return tracking."/>}<ReasonDialog open={!!action} title={action?.title==='In transit'?'Dispatch · enter challan / transport details':action?.title||''} onClose={()=>setAction(null)} onConfirm={reason=>{if(!action)return;setState(s=>audit({...s,entries:s.entries.map(e=>e.id===action.id?{...e,...(action.title==='Confirm handover'?{handover:`${reason} · ${new Date().toLocaleString('en-IN')}`}:{returnState:action.title,returnNote:reason})}:e)},action.title,action.id,reason));notify('Return tracking updated.');}}/></View>;
}
