import React, { useState } from 'react';
import { View, Pressable } from 'react-native';
import { useStore } from './store';
import { C,s,Card,Row,Txt,Button,SectionTitle,Field,Select,Banner,Dialog,Badge,Icon,Empty } from './ui';
import { filterEntries, uid, warranty } from './domain';
import { columns, exportReport } from './reports';
import { EntryRows, Nav } from './Dashboard';
export function Reports({nav,analytics=false}:{nav:Nav;analytics?:boolean}) {
 const {state,setState,isAdmin,dealerId,canEdit,notify,audit}=useStore();const [tab,setTab]=useState(analytics?'Analytics':'Build report'),[type,setType]=useState('All'),[status,setStatus]=useState('All'),[model,setModel]=useState('All'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[format,setFormat]=useState('Excel'),[selected,setSelected]=useState(columns),[save,setSave]=useState(false),[name,setName]=useState(''),[schedule,setSchedule]=useState('Manual'),[busy,setBusy]=useState(false);
 const entries=state.entries.filter(e=>isAdmin||e.dealerId===dealerId),rows=filterEntries(entries,'',type,status,model,from,to);const batteries=state.batteries.filter(b=>isAdmin||b.dealerId===dealerId);
 async function run(){if(state.offline){notify('Reports require online mode.');return;}if(!selected.length){notify('Select at least one export column.');return;}setBusy(true);try{const count=await exportReport(rows,state,format,selected);setState(s=>audit({...s,exports:[{id:uid('EXP'),name:`Battery register · ${format}`,rows:count,date:new Date().toISOString()},...s.exports]},'Report exported','REPORT',`${count} items; ${type}; ${model}; ${status}`));notify(`${count} battery items prepared for export.`);}catch(e){notify('Export could not finish. Please retry or choose another format.');}finally{setBusy(false);}}
 return <View style={{gap:20}}><SectionTitle title="Reports & insights" sub="From daily records to a bigger picture."/><Row style={{flexWrap:'wrap'}}>{['Build report','Saved reports','Export history','Analytics'].map(t=><Button key={t} label={t} kind={tab===t?'primary':'secondary'} onPress={()=>setTab(t)}/>)}</Row>
 {tab==='Build report'&&<><Card><SectionTitle title="Build your register" sub="Your active filters and column order carry through to the export."/><Row style={{flexWrap:'wrap'}}><Select label="Entry type" value={type} options={['All',...state.entryTypes]} onChange={setType}/><Select label="Status" value={status} options={['All','Approved','Submitted','Rejected','Conflict','Cancelled']} onChange={setStatus}/><Select label="Model" value={model} options={['All',...state.models.map(m=>m.id)]} onChange={setModel}/></Row><Row style={{flexWrap:'wrap'}}><Field label="From date" value={from} onChange={setFrom} placeholder="YYYY-MM-DD"/><Field label="To date" value={to} onChange={setTo} placeholder="YYYY-MM-DD"/></Row><SectionTitle title="Export columns" sub="Select columns; move them left to change order."/><View style={s.grid}>{selected.map((col,i)=><Row key={col} style={{borderWidth:1,borderColor:C.line,borderRadius:8,padding:7}}><Button small kind="ghost" label={`Remove ${col}`} icon="check-square" onPress={()=>setSelected(selected.filter(c=>c!==col))}/>{i>0&&<Pressable accessibilityRole="button" accessibilityLabel={`Move ${col} left`} onPress={()=>{const a=[...selected];[a[i-1],a[i]]=[a[i],a[i-1]];setSelected(a);}} style={{padding:10}}><Icon name="arrow-left" size={14}/></Pressable>}</Row>)}</View><Row style={{flexWrap:'wrap',marginVertical:12}}>{columns.filter(c=>!selected.includes(c)).map(c=><Button key={c} label={`Add ${c}`} small kind="secondary" onPress={()=>setSelected([...selected,c])}/>)}</Row><Select label="Export format" value={format} options={['Excel','CSV','PDF']} onChange={setFormat}/><Banner text={format==='Excel'?'Excel exports preserve codes and serials as text, including leading zeroes.':format==='CSV'?'CSV is plain text. Import serial columns as Text in Excel to preserve leading zeroes.':'PDF opens the device print or share dialog.'}/><Row style={{flexWrap:'wrap'}}><Button label={busy?'Preparing export…':'Export report'} icon="download" disabled={busy||!canEdit} onPress={run}/><Button label="Save this report" icon="bookmark" kind="secondary" disabled={!canEdit} onPress={()=>setSave(true)}/></Row></Card><Card><SectionTitle title="Report preview" sub={`${rows.length} entries · ${rows.reduce((n,e)=>n+e.items.length,0)} battery items`}/><EntryRows entries={rows} onOpen={e=>nav('entry',e.id)}/></Card></>}
 {tab==='Saved reports'&&<><Banner text="Report definitions and schedule preferences are saved locally. Automatic delivery will run after a backend scheduler is connected."/>{state.reports.map(r=><Card key={r.id}><SectionTitle title={r.name} sub={`${r.type} · ${r.model} · ${r.schedule}`}/><Button label="Open report" onPress={()=>{setType(r.type);setModel(r.model);setStatus(r.status);setTab('Build report');}}/></Card>)}</>}
 {tab==='Export history'&&<Card>{state.exports.length?state.exports.map(e=><View key={e.id} style={{padding:16,borderBottomWidth:1,borderColor:C.line}}><Row style={{justifyContent:'space-between'}}><Txt style={{fontWeight:'600',fontSize:13}}>{e.name}</Txt><Badge status="Prepared"/></Row><Txt style={s.caption}>{e.rows} items · {new Date(e.date).toLocaleString('en-IN')}</Txt></View>):<Empty title="No exports yet" text="Run a report to create your first export."/>}</Card>}
 {tab==='Analytics'&&<><View style={s.grid}>{[['Battery register',batteries.length],['Replacement entries',entries.filter(e=>e.type==='Replacement').length],['Expiring in 30 days',batteries.filter(b=>warranty(b).status==='Expiring soon').length],['Under review',entries.filter(e=>e.status==='Submitted'||e.status==='Under Review').length]].map(([title,n])=><Card key={title} style={{flex:1,minWidth:150}}><Txt style={s.caption}>{title}</Txt><Txt style={{fontSize:32,marginTop:12}}>{n}</Txt></Card>)}</View><Card><SectionTitle title="Replacements by model" sub="Derived from the current local register."/>{state.models.map(m=>{const count=entries.filter(e=>e.type==='Replacement').flatMap(e=>e.items).filter(i=>i.model===m.id).length;return <Row key={m.id} style={{marginVertical:13}}><Txt style={{width:40,fontSize:12}}>{m.id}</Txt><View style={{flex:1,height:16,backgroundColor:C.bg,borderRadius:4}}><View style={{width:`${Math.min(100,count/Math.max(1,entries.filter(e=>e.type==='Replacement').length)*100)}%`,height:16,backgroundColor:C.gold,borderRadius:4}}/></View><Txt style={{width:24,textAlign:'right',fontSize:12}}>{count}</Txt></Row>;})}</Card><Card><SectionTitle title="Dealer performance"/>{state.dealers.filter(d=>isAdmin||d.id===dealerId).map(d=><Row key={d.id} style={{justifyContent:'space-between',paddingVertical:14,borderBottomWidth:1,borderColor:C.line}}><View><Txt style={{fontSize:13,fontWeight:'600'}}>{d.name}</Txt><Txt style={s.caption}>{d.city}</Txt></View><Txt style={s.caption}>{entries.filter(e=>e.dealerId===d.id).length} entries</Txt><Badge status={d.status}/></Row>)}</Card><Banner text="Failure-rate comparisons need a complete sales denominator and verified failure reasons. This demo shows replacement counts without inventing failure rates."/></>}
 <Dialog title="Save report definition" open={save} onClose={()=>setSave(false)}><Field label="Report name *" value={name} onChange={setName}/><Select label="Schedule preference" value={schedule} options={['Manual','Daily · 9:00','Weekly · Monday','Monthly · 1st']} onChange={setSchedule}/><Button label="Save report" onPress={()=>{if(!name.trim()){notify('Give the report a name.');return;}setState(s=>({...s,reports:[{id:uid('RPT'),name,type,model,status,schedule},...s.reports]}));setSave(false);notify('Report definition saved.');}}/></Dialog></View>;
}
