import React, { useState } from 'react';
import { View, Switch, Pressable, Linking } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { File } from 'expo-file-system';
import * as XLSX from 'xlsx';
import { Platform } from 'react-native';
import { useStore } from './store';
import { C,s,Card,Row,Txt,Button,SectionTitle,Field,Select,Banner,Dialog,ReasonDialog,Badge,Icon,Empty,KeyValue } from './ui';
import { uid,Model,Staff,deriveCode, Role } from './domain';
import { Nav } from './Dashboard';
export function Catalogue() {
 const {state,setState,isAdmin,canEdit,notify,audit}=useStore();const [tab,setTab]=useState('Models'),[edit,setEdit]=useState<Model|null>(null),[raw,setRaw]=useState<any[][]>([]),[filename,setFilename]=useState(''),[message,setMessage]=useState('');
 async function pick(){try{const r=await DocumentPicker.getDocumentAsync({type:['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv','application/vnd.ms-excel'],copyToCacheDirectory:true});if(r.canceled)return;const a=r.assets[0];const bytes=Platform.OS==='web'?await (await fetch(a.uri)).arrayBuffer():await new File(a.uri).arrayBuffer();const book=XLSX.read(bytes,{type:'array',raw:true});setRaw(XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1,raw:false}));setFilename(a.name);setMessage('');}catch{notify('Could not read this spreadsheet. Choose an XLSX or CSV file.');}}
 const headers=(raw[0]||[]).map(String);const staged=raw.slice(1).filter(r=>r.some(Boolean)).map((r,i)=>{const get=(name:string)=>String(r[headers.indexOf(name)]||'').trim();const code=get('Code'),model=get('Model'),dealerId=get('Dealer ID');const errors:string[]=[];if(!/^\d{8}$/.test(code)||!deriveCode(code).mfg)errors.push('Invalid code');if(!state.models.some(m=>m.id===model))errors.push('Unknown model');if(!state.dealers.some(d=>d.id===dealerId))errors.push('Unknown dealer');if(state.batteries.some(b=>b.code===code)||raw.slice(1,i+1).some(x=>String(x[headers.indexOf('Code')])===code))errors.push('Duplicate code');return {code,model,dealerId,serial:get('Serial No')||deriveCode(code).serial,mfg:deriveCode(code).mfg,errors};});
 return <View style={{gap:20}}><SectionTitle title="Battery catalogue" sub="Model specifications and serial reference data."/><Row style={{flexWrap:'wrap'}}>{(isAdmin?['Models','Serial rules','Bulk import']:['Models','Serial rules']).map(t=><Button key={t} label={t} kind={tab===t?'primary':'secondary'} onPress={()=>setTab(t)}/>)}</Row>
 {tab==='Models'&&<>{isAdmin&&canEdit&&<Button label="Add model" icon="plus" onPress={()=>setEdit({id:'',type:'IT',capacity:'',months:24,threshold:5,active:true})}/>}<View style={s.grid}>{state.models.map(m=><Card key={m.id} style={{flex:1,minWidth:240}}><Row style={{justifyContent:'space-between'}}><View style={{backgroundColor:C.goldSoft,padding:15,borderRadius:12}}><Icon name="battery-charging" size={26} color={C.ink}/></View><Badge status={m.active?'Active':'Inactive'}/></Row><Txt style={{fontSize:30,fontWeight:'600',marginTop:20}}>{m.id}</Txt><Txt style={s.caption}>{m.type} · {m.capacity}</Txt><KeyValue label="Standard warranty" value={`${m.months} months · original sale`}/>{isAdmin&&canEdit&&<Button label={`Edit ${m.id}`} kind="secondary" onPress={()=>setEdit({...m})}/>}</Card>)}</View></>}
 {tab==='Serial rules'&&<Card><SectionTitle title="Battery code → serial → manufacturing month"/><Banner text="Demo rule: 8 numeric digits, YYMM + 4-digit serial. Final family-specific rules should be supplied by Felix before connecting production data."/><Row style={{flexWrap:'wrap'}}><KeyValue label="Battery code" value="21030047"/><KeyValue label="Serial (text)" value="0047"/><KeyValue label="Manufacturing month" value="2021-03"/></Row><Txt style={s.caption}>Leading zeroes are retained. Duplicate active codes and old/new equality are blocked. Unknown old serials are flagged for review.</Txt></Card>}
 {tab==='Bulk import'&&<Card><SectionTitle title="Import serial register" sub="Review every row in staging before committing to the demo registry."/><Banner text="Required columns: Code, Model, Dealer ID. Optional: Serial No. Format code and serial columns as text in Excel. Unknown historical warranty dates remain unknown."/><Button label="Choose XLSX / CSV" icon="upload" disabled={!canEdit} onPress={pick}/>{filename&&<View style={{marginTop:20,gap:15}}><Txt style={{fontWeight:'600'}}>{filename}</Txt><Txt style={s.caption}>{staged.length} staged rows · {staged.filter(r=>r.errors.length).length} exceptions</Txt>{staged.map((r,i)=><Row key={i} style={{paddingVertical:10,borderBottomWidth:1,borderColor:C.line}}><Txt style={{flex:1,fontSize:12}}>{r.code} · {r.model} · {r.dealerId}</Txt><Badge status={r.errors.length?r.errors.join(', '):'Ready'}/></Row>)}{message&&<Banner tone="success" text={message}/>}<Button label="Confirm import" disabled={!staged.length||staged.some(r=>r.errors.length>0)||!canEdit} onPress={()=>{setState(s=>audit({...s,batteries:[...s.batteries,...staged.map(({errors,...r})=>({...r,customer:'',state:'Available'}))]},'Serial import','IMPORT',`${filename}: ${staged.length} rows committed`));setMessage('All staged serials imported. Warranty dates remain not on record.');setRaw([]);notify('Serial register imported.');}}/></View>}</Card>}
 <Dialog open={!!edit} title="Battery model" onClose={()=>setEdit(null)}>{edit&&<><Field label="Model ID *" value={edit.id} onChange={id=>setEdit({...edit,id})}/><Field label="Battery type" value={edit.type} onChange={type=>setEdit({...edit,type})}/><Field label="Capacity *" value={edit.capacity} onChange={capacity=>setEdit({...edit,capacity})}/><Row style={{justifyContent:'space-between',marginBottom:20}}><Txt>Active in new entries</Txt><Switch value={edit.active} onValueChange={active=>setEdit({...edit,active})}/></Row><Button label="Save model" onPress={()=>{if(!edit.id.trim()||!edit.capacity.trim()){notify('Model ID and capacity are required.');return;}setState(s=>audit({...s,models:[...s.models.filter(m=>m.id!==edit.id),edit]},'Model saved',edit.id,'Catalogue updated'));setEdit(null);notify('Model saved.');}}/></>}</Dialog></View>;
}
export function Notifications() {
 const {state,setState,isAdmin,dealerId,canEdit,audit,notify}=useStore();const [title,setTitle]=useState(''),[body,setBody]=useState(''),[audience,setAudience]=useState('All dealers');
 const notices=state.notices.filter(n=>isAdmin||!n.dealerId||n.dealerId===dealerId);
 return <View style={{gap:20}}><SectionTitle title="Notification centre" sub="Updates that keep everyone connected."/><Button label="Mark all as read" kind="secondary" onPress={()=>setState(s=>({...s,notices:s.notices.map(n=>notices.some(x=>x.id===n.id)?{...n,read:true}:n)}))}/>{notices.map(n=><Card key={n.id}><Row style={{justifyContent:'space-between'}}><SectionTitle title={n.title}/>{!n.read&&<Badge status="Unread"/>}</Row><Txt style={s.caption}>{n.body}</Txt></Card>)}{isAdmin&&canEdit&&<Card><SectionTitle title="Compose announcement" sub="Creates in-app demo notifications. No SMS, email, or push messages are sent."/><Select label="Audience" value={audience} options={['All dealers',...state.dealers.map(d=>d.name)]} onChange={setAudience}/><Field label="Announcement title *" value={title} onChange={setTitle}/><Field label="Message *" value={body} onChange={setBody} multiline/><Button label="Post in-app announcement" onPress={()=>{if(!title.trim()||!body.trim()){notify('Add a title and message.');return;}setState(s=>audit({...s,notices:[{id:uid('N'),title,body,route:'notifications',read:false,dealerId:state.dealers.find(d=>d.name===audience)?.id},...s.notices]},'In-app announcement','NOTICES',title));setTitle('');setBody('');notify('Announcement added to the local inbox.');}}/></Card>}</View>;
}
export function AuditLog() {
 const {state,isAdmin}=useStore();const [query,setQuery]=useState('');if(!isAdmin)return <Empty title="Admin access required"/>;
 return <View style={{gap:20}}><SectionTitle title="Audit trail" sub="Who changed what, when, and why."/><Card><Field label="Filter audit events" value={query} onChange={setQuery} placeholder="Actor, action, reference, or reason"/></Card>{state.audits.filter(a=>[a.actor,a.action,a.ref,a.reason].some(v=>v.toLowerCase().includes(query.toLowerCase()))).map(a=><Card key={a.id}><SectionTitle title={a.action} sub={`${a.actor} · ${new Date(a.at).toLocaleString('en-IN')}`}/><KeyValue label="Record reference" value={a.ref}/><KeyValue label="Reason" value={a.reason}/>{(a.before||a.after)&&<Row style={{flexWrap:'wrap'}}><KeyValue label="Before" value={a.before}/><KeyValue label="After" value={a.after}/></Row>}</Card>)}</View>;
}
export function Team() {
 const {state,setState,isAdmin,dealerId,role,canEdit,notify,audit}=useStore();const [editing,setEditing]=useState<Staff|null>(null),[decision,setDecision]=useState<{id:string;status:string}|null>(null);
 if(isAdmin&&role!=='Main Admin')return <Empty title="Main Admin access only" text="Admin account management is not available to this role."/>;
 const users=state.staff.filter(u=>isAdmin?!u.dealerId:u.dealerId===dealerId);
 return <View style={{gap:20}}><SectionTitle title={isAdmin?'Administrators & roles':'Your dealership team'} sub="Access follows each person’s responsibilities."/>{canEdit&&<Button label={isAdmin?'Add administrator':'Add team member'} icon="user-plus" onPress={()=>setEditing({id:uid('USR'),name:'',email:'',role:isAdmin?'Co-Admin':'Dealer User',status:'Active',dealerId:isAdmin?undefined:dealerId,permissions:['Entries']})}/>}<Banner text="These are demo account records and UI permissions. Real invites, authentication, and API authorization require a backend."/>{users.map(u=><Card key={u.id}><SectionTitle title={u.name} sub={`${u.email} · ${u.role}`}/><Badge status={u.status}/><KeyValue label="Permissions" value={u.permissions.join(', ')}/>{canEdit&&u.role!=='Main Admin'&&<Row style={{flexWrap:'wrap'}}><Button label="Edit permissions" kind="secondary" onPress={()=>setEditing({...u})}/>{['Active','Temporarily Blocked','Inactive','Soft Deleted'].filter(x=>x!==u.status).map(status=><Button key={status} label={status==='Active'?'Restore / activate':status} kind="ghost" onPress={()=>setDecision({id:u.id,status})}/>)}</Row>}</Card>)}
 <Dialog title="Account & permissions" open={!!editing} onClose={()=>setEditing(null)}>{editing&&<><Field label="Full name *" value={editing.name} onChange={name=>setEditing({...editing,name})}/><Field label="Email *" value={editing.email} onChange={email=>setEditing({...editing,email})}/><Select label="Role" value={editing.role} options={isAdmin?['Co-Admin','Read-only','Operations','Inventory Manager']:['Dealer User','Dealer Manager']} onChange={role=>setEditing({...editing,role})}/>{['Entries','Dealers','Inventory','Reports','Customers'].map(p=><Row key={p} style={{justifyContent:'space-between',marginBottom:12}}><Txt>{p}</Txt><Switch value={editing.permissions.includes(p)} onValueChange={enabled=>setEditing({...editing,permissions:enabled?[...editing.permissions,p]:editing.permissions.filter(x=>x!==p)})}/></Row>)}<Button label="Save account" onPress={()=>{if(!editing.name.trim()||!/^\S+@\S+\.\S+$/.test(editing.email)){notify('A name and valid email are required.');return;}setState(s=>audit({...s,staff:[editing,...s.staff.filter(u=>u.id!==editing.id)]},'Account permissions saved',editing.id,'Account and module access updated'));setEditing(null);notify('Demo account saved.');}}/></>}</Dialog><ReasonDialog title={`Set account ${decision?.status||''}`} open={!!decision} onClose={()=>setDecision(null)} onConfirm={reason=>{if(!decision)return;setState(s=>audit({...s,staff:s.staff.map(u=>u.id===decision.id?{...u,status:decision.status}:u)},'Account status changed',decision.id,reason));}}/></View>;
}
export function Profile({nav,onSignOut}:{nav:Nav;onSignOut:()=>void}) {
 const {state,setState,dealerId,isAdmin,role,notify,audit}=useStore();const dealer=state.dealers.find(d=>d.id===dealerId)!;const [edit,setEdit]=useState({...dealer}),[city,setCity]=useState(''),[type,setType]=useState('');
 async function attach(){try{const r=await DocumentPicker.getDocumentAsync({type:['application/pdf','image/*'],copyToCacheDirectory:true});if(!r.canceled){setEdit(d=>({...d,documents:[...(d.documents||[]),r.assets[0].name]}));notify('Document selected. Save profile to retain its name.');}}catch{notify('Document picker unavailable.');}}
 return <View style={{gap:20}}><SectionTitle title="Profile & preferences" sub="Your workspace, set up for the way you work."/><Card><Row style={{justifyContent:'space-between'}}><View><Txt style={{fontSize:23,fontWeight:'600'}}>{isAdmin?'S. Deshpande':dealer.name}</Txt><Txt style={s.caption}>{isAdmin?role:`${dealer.id} · ${dealer.city}`}</Txt></View><Badge status={isAdmin?'Active':dealer.status}/></Row><View style={s.divider}/><Select label="Interface labels" value={state.language} options={['English','मराठी']} onChange={v=>setState(s=>({...s,language:v as any}))}/><Banner text="Marathi navigation and entry-type labels are available. Detailed operational content remains in English."/><Row style={{flexWrap:'wrap'}}><Button label="Manage team" icon="users" kind="secondary" onPress={()=>nav('team')}/><Button label="Sync centre" icon="refresh-cw" kind="secondary" onPress={()=>nav('sync')}/><Button label="Sign out" icon="log-out" kind="ghost" onPress={onSignOut}/></Row></Card>
 {!isAdmin&&<Card><SectionTitle title="Business profile" sub="Dealer code, city, and status are managed by the admin."/><Field label="Contact person" value={edit.contact} onChange={contact=>setEdit({...edit,contact})}/><Field label="Email" value={edit.email} onChange={email=>setEdit({...edit,email})}/><Field label="Address" value={edit.address} onChange={address=>setEdit({...edit,address})} multiline/><KeyValue label="Documents" value={edit.documents?.join(', ')||'No documents selected'}/><Row style={{flexWrap:'wrap'}}><Button label="Select document" icon="paperclip" kind="secondary" onPress={attach}/><Button label="Save profile" onPress={()=>{if(!edit.contact.trim()||!/^\S+@\S+\.\S+$/.test(edit.email)){notify('Enter a contact name and valid email.');return;}setState(s=>audit({...s,dealers:s.dealers.map(d=>d.id===dealerId?{...d,contact:edit.contact,email:edit.email,address:edit.address,documents:edit.documents}:d)},'Profile updated',dealerId,'Dealer updated contact details'));notify('Business profile saved.');}}/></Row><Txt style={[s.caption,{marginTop:12}]}>Document metadata is saved locally; production document storage is not connected.</Txt></Card>}
 <Card><SectionTitle title="Security & access"/><KeyValue label="Authentication mode" value="Local demo session"/><KeyValue label="Production two-factor authentication" value="Not connected"/><Banner text="Use the sign-in screen to preview password recovery and OTP verification. Demo accounts use code 123456; no credentials or SMS are sent."/><Button label="Preview sign-in & recovery" kind="secondary" onPress={onSignOut}/></Card>
 {role==='Main Admin'&&<Card><SectionTitle title="Reference / master data"/><Field label="New city / territory" value={city} onChange={setCity}/><Button label="Add city" kind="secondary" onPress={()=>{if(city.trim()&&!state.cities.includes(city.trim())){setState(s=>audit({...s,cities:[...s.cities,city.trim()]},'City added','MASTER',city));setCity('');}}}/><Txt style={[s.caption,{marginVertical:15}]}>{state.cities.join(' · ')}</Txt><Field label="New entry type" value={type} onChange={setType}/><Button label="Add entry type" kind="secondary" onPress={()=>{if(type.trim()&&!state.entryTypes.includes(type.trim())){setState(s=>audit({...s,entryTypes:[...s.entryTypes,type.trim()]},'Entry type added','MASTER',type));setType('');}}}/></Card>}
 <Card><SectionTitle title="System health"/><Row style={{flexWrap:'wrap'}}><KeyValue label="Application" value="Expo · React Native"/><KeyValue label="Local data" value="Persistent demo store"/><KeyValue label="API / SMS / email / OCR" value="Not connected"/><KeyValue label="Pending sync" value={String(state.entries.filter(e=>e.status==='Pending sync').length)}/></Row><Button label="Review sync queue" kind="secondary" onPress={()=>nav('sync')}/></Card></View>;
}
