import React, { useState } from 'react';
import { View, Text, Pressable, TextInput, StyleSheet, ScrollView, Modal, useWindowDimensions, ActivityIndicator } from 'react-native';
import { Feather } from '@expo/vector-icons';
import Svg, { Path, Rect, Line, Circle } from 'react-native-svg';
export const C={bg:'#F5F6F8',white:'#FFFFFF',ink:'#19232C',muted:'#77818E',line:'#E8EBEE',gold:'#F3B641',goldSoft:'#FFF5DD',green:'#24836A',greenSoft:'#EAF6F0',blue:'#3868A3',blueSoft:'#ECF2FA',red:'#BE554D',redSoft:'#FCEFEB',purple:'#7C68A8',nav:'#18232C'};
export type IconName=React.ComponentProps<typeof Feather>['name'];
export const Icon=({name,size=19,color=C.muted}:{name:IconName;size?:number;color?:string})=><Feather name={name} size={size} color={color}/>;
export const Txt=({children,style,...props}:React.ComponentProps<typeof Text>)=><Text {...props} style={[s.text,style]}>{children}</Text>;
export const Row=({children,style}: {children:React.ReactNode;style?:any})=><View style={[s.row,style]}>{children}</View>;
export const Card=({children,style}: {children:React.ReactNode;style?:any})=><View style={[s.card,style]}>{children}</View>;
export const Label=({children}:{children:React.ReactNode})=><Txt style={s.label}>{children}</Txt>;
export function Button({label,onPress,icon,kind='primary',disabled=false,small=false,style}:{label:string;onPress:()=>void;icon?:IconName;kind?:'primary'|'secondary'|'ghost'|'danger'|'dark';disabled?:boolean;small?:boolean;style?:any}) {
 const fg=kind==='dark'?'white':kind==='danger'?C.red:C.ink;
 return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={({pressed,hovered}:any)=>[s.button,small&&{paddingHorizontal:12,minHeight:40},kind==='primary'&&{backgroundColor:C.gold,borderColor:C.gold},kind==='dark'&&{backgroundColor:C.ink,borderColor:C.ink},kind==='ghost'&&{backgroundColor:'transparent',borderColor:'transparent'},kind==='danger'&&{backgroundColor:C.redSoft,borderColor:C.redSoft},(pressed||hovered)&&{opacity:.78},disabled&&{opacity:.4},style]}>{icon&&<Icon name={icon} color={fg} size={16}/>}<Txt style={{fontSize:small?12:13,fontWeight:'600',color:fg}}>{label}</Txt></Pressable>;
}
export const IconButton=({name,onPress,label}:{name:IconName;onPress:()=>void;label:string})=><Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={s.iconButton}><Icon name={name} color={C.ink}/></Pressable>;
export function Badge({status}:{status:string}) {
 let color=C.muted,bg='#F0F2F4';
 if(/Approved|Active|Available|Synced|Closed|Delivered/.test(status)){color=C.green;bg=C.greenSoft;}
 else if(/Pending|Submitted|Expiring|At dealer|Low|Allocated/.test(status)){color='#AD7C20';bg=C.goldSoft;}
 else if(/Rejected|Conflict|Expired|Suspended|Failed|Cancelled/.test(status)){color=C.red;bg=C.redSoft;}
 else if(/Review|Repair|Transit|Replacement|Corrected/.test(status)){color=C.blue;bg=C.blueSoft;}
 return <View style={[s.badge,{backgroundColor:bg}]}><View style={{width:5,height:5,borderRadius:3,backgroundColor:color}}/><Txt style={{color,fontSize:10,fontWeight:'600'}}>{status}</Txt></View>;
}
export function Field({label,value,onChange,placeholder,error,multiline=false,secure=false,numeric=false,editable=true}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;error?:string;multiline?:boolean;secure?:boolean;numeric?:boolean;editable?:boolean}) {
 return <View style={{gap:7,marginBottom:16,flexGrow:1}}><Label>{label}</Label><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor="#9CA4AD" secureTextEntry={secure} keyboardType={numeric?'numeric':'default'} autoCapitalize="none" editable={editable} multiline={multiline} style={[s.input,multiline&&{height:88,textAlignVertical:'top',paddingTop:12},!editable&&{backgroundColor:C.bg,color:C.muted},!!error&&{borderColor:C.red}]}/>{error&&<Txt style={{color:C.red,fontSize:11}}>{error}</Txt>}</View>;
}
export function Select({label,value,options,onChange}:{label?:string;value:string;options:string[];onChange:(v:string)=>void}) {
 const [open,setOpen]=useState(false);
 return <View style={{gap:7,marginBottom:label?16:0,flexGrow:1}}>{label&&<Label>{label}</Label>}<Pressable accessibilityRole="button" accessibilityLabel={`${label||'Filter'}: ${value}`} onPress={()=>setOpen(true)} style={s.input}><Row style={{justifyContent:'space-between',flex:1}}><Txt style={{fontSize:12}}>{value}</Txt><Icon name="chevron-down" size={15}/></Row></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={s.overlay}><View style={[s.card,{width:'100%',maxWidth:430,maxHeight:'75%'}]}><Row style={{justifyContent:'space-between',marginBottom:12}}><Txt style={s.title}>{label||'Choose a filter'}</Txt><IconButton name="x" label="Close options" onPress={()=>setOpen(false)}/></Row><ScrollView>{options.map(o=><Pressable accessibilityRole="button" key={o} onPress={()=>{onChange(o);setOpen(false);}} style={{padding:14,borderRadius:8,backgroundColor:o===value?C.goldSoft:'white',minHeight:46}}><Row style={{justifyContent:'space-between'}}><Txt>{o}</Txt>{o===value&&<Icon name="check" color={C.green}/>}</Row></Pressable>)}</ScrollView></View></View></Modal></View>;
}
export const SectionTitle=({title,sub,action,onPress}:{title:string;sub?:string;action?:string;onPress?:()=>void})=><Row style={{justifyContent:'space-between',marginBottom:18,flexWrap:'wrap'}}><View style={{gap:5}}><Txt style={s.title}>{title}</Txt>{sub&&<Txt style={s.caption}>{sub}</Txt>}</View>{action&&<Button kind="ghost" small label={action} icon="arrow-right" onPress={onPress!}/>}</Row>;
export const Banner=({text,tone='info'}:{text:string;tone?:'info'|'warning'|'success'|'danger'})=><Row style={{alignItems:'flex-start',padding:14,borderRadius:10,backgroundColor:tone==='warning'?C.goldSoft:tone==='success'?C.greenSoft:tone==='danger'?C.redSoft:C.blueSoft,gap:10,marginBottom:16}}><Icon name={tone==='success'?'check-circle':'info'} size={16} color={tone==='danger'?C.red:C.blue}/><Txt style={{fontSize:12,lineHeight:19,flex:1}}>{text}</Txt></Row>;
export const Empty=({title='Nothing here yet',text='Your records will appear here.',action,onPress}:{title?:string;text?:string;action?:string;onPress?:()=>void})=><View style={{padding:36,alignItems:'center',gap:12}}><View style={s.emptyIcon}><Icon name="inbox" size={26}/></View><Txt style={s.title}>{title}</Txt><Txt style={[s.caption,{textAlign:'center',maxWidth:360}]}>{text}</Txt>{action&&<Button label={action} onPress={onPress!}/>}</View>;
export function Dialog({title,children,open,onClose}:{title:string;children:React.ReactNode;open:boolean;onClose:()=>void}) {return <Modal transparent visible={open} animationType="fade" onRequestClose={onClose}><View style={s.overlay}><View style={[s.card,{width:'100%',maxWidth:680,maxHeight:'90%',padding:24}]}><Row style={{justifyContent:'space-between',marginBottom:20}}><Txt style={s.title}>{title}</Txt><IconButton name="x" onPress={onClose} label="Close dialog"/></Row><ScrollView keyboardShouldPersistTaps="handled">{children}</ScrollView></View></View></Modal>;}
export function ReasonDialog({title,open,onClose,onConfirm,extra}:{title:string;open:boolean;onClose:()=>void;onConfirm:(reason:string)=>void;extra?:React.ReactNode}) {
 const [reason,setReason]=useState(''),[error,setError]=useState('');
 return <Dialog title={title} open={open} onClose={onClose}>{extra}<Field label="Reason *" value={reason} onChange={setReason} multiline error={error} placeholder="Add context for the audit trail"/><Row style={{justifyContent:'flex-end'}}><Button label="Cancel" kind="secondary" onPress={onClose}/><Button label="Confirm decision" onPress={()=>{if(reason.trim().length<5){setError('Enter a reason with at least 5 characters.');return;}onConfirm(reason.trim());setReason('');setError('');onClose();}}/></Row></Dialog>;
}
export const KeyValue=({label,value}:{label:string;value?:string})=><View style={{gap:6,minWidth:130,flex:1,paddingVertical:8}}><Label>{label}</Label><Txt style={{fontSize:13,fontWeight:'500'}}>{value||'—'}</Txt></View>;
export function BatteryArt({size=220}:{size?:number}) {return <Svg width={size} height={size*.74} viewBox="0 0 260 195"><Circle cx="138" cy="106" r="82" fill="#FFFFFF" opacity=".04"/><Circle cx="138" cy="106" r="63" stroke="#FFFFFF" strokeDasharray="3 7" strokeWidth="1" opacity=".12" fill="none"/><Path d="M41 70 L158 50 L216 78 L102 104 Z" fill="#55616B"/><Path d="M41 70 L102 104 L102 180 L41 147 Z" fill="#2B363F"/><Path d="M102 104 L216 78 L216 155 L102 180 Z" fill="#3A4650"/><Path d="M39 65 L157 45 L220 73 L102 100 Z" fill="#76818A"/><Path d="M39 65 L102 100 L102 111 L39 76 Z" fill="#1A252F"/><Path d="M102 100 L220 73 L220 84 L102 111 Z" fill="#27323C"/><Path d="M65 59 L65 45 L86 41 L97 46 L97 60 L77 65 Z" fill="#D7DBDF"/><Path d="M169 55 L169 42 L190 38 L202 44 L202 56 L181 60 Z" fill="#C16150"/><Path d="M110 123 L205 102 L205 146 L110 167 Z" fill="#E8AD3D"/><Path d="M150 115 L137 142 L151 138 L144 156 L170 129 L153 133 L162 112 Z" fill="#28343E"/><Line x1="56" y1="95" x2="56" y2="145" stroke="#45515C" strokeWidth="4"/><Line x1="68" y1="101" x2="68" y2="151" stroke="#45515C" strokeWidth="4"/><Line x1="80" y1="108" x2="80" y2="158" stroke="#45515C" strokeWidth="4"/></Svg>;}
export const s=StyleSheet.create({text:{fontFamily:'System',fontSize:14,color:C.ink},row:{flexDirection:'row',alignItems:'center',gap:10},card:{backgroundColor:'white',borderWidth:1,borderColor:C.line,borderRadius:14,padding:22},title:{fontSize:16,fontWeight:'600',letterSpacing:-.3},caption:{fontSize:12,color:C.muted,lineHeight:19},label:{fontSize:11,fontWeight:'500',color:C.muted},button:{minHeight:44,borderRadius:8,borderWidth:1,borderColor:C.line,backgroundColor:'white',paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},iconButton:{width:44,height:44,justifyContent:'center',alignItems:'center',borderRadius:9},input:{minHeight:44,height:44,borderWidth:1,borderColor:'#DEE3E8',borderRadius:8,paddingHorizontal:12,backgroundColor:'white',fontFamily:'System',fontSize:13,color:C.ink,justifyContent:'center'},badge:{alignSelf:'flex-start',paddingHorizontal:9,paddingVertical:5,borderRadius:5,flexDirection:'row',alignItems:'center',gap:5},overlay:{flex:1,backgroundColor:'#15212C88',justifyContent:'center',alignItems:'center',padding:18},emptyIcon:{width:58,height:58,borderRadius:20,backgroundColor:C.bg,alignItems:'center',justifyContent:'center'},grid:{flexDirection:'row',flexWrap:'wrap',gap:16},divider:{height:1,backgroundColor:C.line,marginVertical:18}});

